import {GpuSession,GpuTimer} from '../gpu/device';
import {RevisionGate} from '../gpu/contracts';
import shaderSource from '../../shaders/gpu/transparency.wgsl?raw';
import resolveSource from '../../shaders/gpu/transparency-resolve.wgsl?raw';
import presentSource from '../../shaders/gpu/present.wgsl?raw';
import type {LightingState} from './state';
import type {LightingReport,LightingInspection} from './renderer';
import {BACKGROUND,layersAt,composite,exactComposite,weightedComposite} from './math';
export class TransparencyWebGPURenderer {
 canvas=document.createElement('canvas');session!:GpuSession;timer!:GpuTimer;layers:GPUBuffer[]=[];displayUniforms!:GPUBuffer;debug!:GPUBuffer;accum!:GPUTexture;reveal!:GPUTexture;sorted!:GPUTexture;image!:GPUTexture;pipelines:GPURenderPipeline[]=[];groups:GPUBindGroup[]=[];compute!:GPUComputePipeline;inspectPipeline!:GPUComputePipeline;computeGroup!:GPUBindGroup;display!:GPURenderPipeline;displayGroup!:GPUBindGroup;state:LightingState;ready=false;pending=true;paused=false;visible=true;disposed=false;lost=false;frame=0;selected:[number,number]|null=null;inspection:LightingInspection|null=null;gate=new RevisionGate();observer:IntersectionObserver;
 private constructor(public host:HTMLElement,s:LightingState,public report:(r:LightingReport)=>void){this.state=structuredClone(s);this.canvas.width=480;this.canvas.height=160;host.append(this.canvas);this.canvas.setAttribute('aria-label','WebGPU 透明合成：对象顺序、逐像素排序和 WBOIT');this.canvas.addEventListener('click',this.clicked);this.observer=new IntersectionObserver(([e])=>{this.visible=e.isIntersecting;if(this.visible)this.request();else{cancelAnimationFrame(this.frame);this.frame=0;}});this.observer.observe(host);}
 static async create(host:HTMLElement,s:LightingState,report:(r:LightingReport)=>void){const e=new TransparencyWebGPURenderer(host,s,report);try{await e.initialize();return e;}catch(error){e.dispose();throw error;}}
 private async initialize(){this.session=await GpuSession.create(this.canvas,error=>{this.lost=true;this.setPaused(true);this.gate.advance();this.report({ready:false,pending:false,error,inspection:null});});const d=this.session.device;this.timer=new GpuTimer(this.session);this.layers=[0,1,2].map(id=>this.session.buffer('transparent layer '+id,32,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST));this.debug=this.session.buffer('transparent inspection',80,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC);this.displayUniforms=this.session.buffer('transparency display',16,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);const usage=GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING;this.accum=this.session.texture('WBOIT accumulator',160,160,'rgba16float',usage);this.reveal=this.session.texture('WBOIT transmittance',160,160,'rgba16float',usage);this.sorted=this.session.texture('object-order reference',160,160,'rgba16float',usage);this.image=this.session.texture('composited linear image',480,160,'rgba32float',GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.TEXTURE_BINDING);
 const [shader,resolve,display]=await Promise.all([this.session.shader(shaderSource,'transparent blending'),this.session.shader(shaderSource+resolveSource,'transparent resolve'),this.session.shader(presentSource,'transparent display')]);const layout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}}]});const pl=d.createPipelineLayout({bindGroupLayouts:[layout]});const blends:GPUBlendState[]=[{color:{srcFactor:'one',dstFactor:'one'},alpha:{srcFactor:'one',dstFactor:'one'}},{color:{srcFactor:'zero',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'zero',dstFactor:'one-minus-src-alpha'}},{color:{srcFactor:'one',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha'}}];this.pipelines=await Promise.all(['accumulate','revealage','ordered'].map((entryPoint,i)=>d.createRenderPipelineAsync({layout:pl,vertex:{module:shader,entryPoint:'vertex'},fragment:{module:shader,entryPoint,targets:[{format:'rgba16float',blend:blends[i]}]},primitive:{topology:'triangle-list'}})));this.groups=this.layers.map(buffer=>d.createBindGroup({layout,entries:[{binding:0,resource:{buffer}}]}));
 const cl=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.COMPUTE,buffer:{type:'uniform'}},...[1,2,3].map(binding=>({binding,visibility:GPUShaderStage.COMPUTE,texture:{sampleType:'unfilterable-float' as const}})),{binding:4,visibility:GPUShaderStage.COMPUTE,storageTexture:{format:'rgba32float',access:'write-only'}},{binding:5,visibility:GPUShaderStage.COMPUTE,buffer:{type:'storage'}}]});const cp=d.createPipelineLayout({bindGroupLayouts:[cl]});this.compute=await d.createComputePipelineAsync({layout:cp,compute:{module:resolve,entryPoint:'render'}});this.inspectPipeline=await d.createComputePipelineAsync({layout:cp,compute:{module:resolve,entryPoint:'inspect'}});this.computeGroup=d.createBindGroup({layout:cl,entries:[{binding:0,resource:{buffer:this.layers[0]}},{binding:1,resource:this.accum.createView()},{binding:2,resource:this.reveal.createView()},{binding:3,resource:this.sorted.createView()},{binding:4,resource:this.image.createView()},{binding:5,resource:{buffer:this.debug}}]});
 const dl=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'unfilterable-float'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}}]});this.display=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[dl]}),vertex:{module:display,entryPoint:'vertex'},fragment:{module:display,entryPoint:'fragment',targets:[{format:this.session.format}]},primitive:{topology:'triangle-list'}});this.displayGroup=d.createBindGroup({layout:dl,entries:[{binding:0,resource:this.image.createView()},{binding:1,resource:{buffer:this.displayUniforms}}]});const a=this.session.adapter;this.report({state:this.state,device:`WebGPU · ${a.vendor} / ${a.architecture} · ${a.fallback?'软件适配器':'非软件回退'}`});this.write();this.request();}
 private write(){if(!this.layers.length)return;for(let id=0;id<3;id++)this.session.device.queue.writeBuffer(this.layers[id],0,new Float32Array([this.state.alpha,this.state.power,+this.state.crossing,id,...(this.selected??[.5,.5]),0,0]));this.session.device.queue.writeBuffer(this.displayUniforms,0,new Float32Array([480,160,0,2]));}
 update(state:LightingState){if(this.disposed)return;this.state=structuredClone(state);this.pending=true;this.inspection=null;this.gate.advance();this.write();this.report({state:this.state,pending:true,inspection:null,gpuMs:null});this.request();}
 private request(){if(!this.compute||this.disposed||this.lost||this.paused||!this.visible||!this.pending||this.frame)return;this.frame=requestAnimationFrame(()=>{this.frame=0;this.render();});}
 setPaused(value:boolean){this.paused=value;cancelAnimationFrame(this.frame);this.frame=0;this.report({paused:value});if(!value)this.request();}
 step(){if(!this.disposed&&!this.lost&&this.compute)this.render();}
 private present(cmd:GPUCommandEncoder){const p=cmd.beginRenderPass({colorAttachments:[{view:this.session.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});p.setPipeline(this.display);p.setBindGroup(0,this.displayGroup);p.draw(3);p.end();}
 private render(){const start=performance.now(),cmd=this.session.device.createCommandEncoder(),order=this.state.reverse?[0,1,2]:[2,1,0],query=this.timer.writes(),token=JSON.stringify(this.state);this.write();for(let stage=0;stage<3;stage++){const target=[this.accum,this.reveal,this.sorted][stage],clearValue:GPUColor=stage===0?[0,0,0,0]:stage===1?[1,1,1,1]:[...BACKGROUND,1];const timestampWrites=query&&stage<2?(stage===0?{querySet:query.querySet,beginningOfPassWriteIndex:0}:{querySet:query.querySet,endOfPassWriteIndex:1}):undefined;const pass=cmd.beginRenderPass({timestampWrites,colorAttachments:[{view:target.createView(),loadOp:'clear',storeOp:'store',clearValue}]});pass.setPipeline(this.pipelines[stage]);for(const id of order){pass.setBindGroup(0,this.groups[id]);pass.draw(3);}pass.end();}const timed=this.timer.resolve(cmd);const p=cmd.beginComputePass();p.setPipeline(this.compute);p.setBindGroup(0,this.computeGroup);p.dispatchWorkgroups(60,20);p.end();this.present(cmd);this.session.device.queue.submit([cmd.finish()]);this.ready=true;this.pending=false;this.report({ready:true,pending:false,cpuMs:performance.now()-start});if(timed)this.timer.read().then(gpuMs=>{if(!this.disposed&&token===JSON.stringify(this.state))this.report({gpuMs});}).catch(()=>{});if(this.selected)void this.pick(...this.selected);}
 async pick(u=.5,v=.5){if(!this.ready||this.pending||this.lost)return;const uv:[number,number]=[(Math.min(159,Math.max(0,Math.floor(u*160)))+.5)/160,(Math.min(159,Math.max(0,Math.floor(v*160)))+.5)/160];this.selected=uv;this.inspection=null;this.report({inspection:null});const token=this.gate.advance();this.write();const cmd=this.session.device.createCommandEncoder(),p=cmd.beginComputePass();p.setPipeline(this.inspectPipeline);p.setBindGroup(0,this.computeGroup);p.dispatchWorkgroups(1);p.end();this.session.device.queue.submit([cmd.finish()]);try{const data=new Float32Array(await this.session.readBuffer(this.debug,80));if(this.disposed||!this.gate.accepts(token))return;const layers=layersAt(...uv,this.state.alpha,this.state.crossing),order=[...layers].sort((a,b)=>this.state.reverse?a.id-b.id:b.id-a.id);this.inspection={uv,gpu:[0,1,2].map(i=>Array.from(data.slice(i*4,i*4+3))),layers,cpu:[composite(order),exactComposite(layers),weightedComposite(layers,this.state.power).color],accum:Array.from(data.slice(12,16)),reveal:data[16]};this.report({inspection:this.inspection});}catch(e){if(!this.disposed&&this.gate.accepts(token))this.report({error:'WebGPU 检查失败：'+String(e),inspection:null});}}
 generateReference(){}cancelReference(){}
 private clicked=(e:MouseEvent)=>{const b=this.canvas.getBoundingClientRect();void this.pick(((e.clientX-b.left)/b.width*3)%1,1-(e.clientY-b.top)/b.height);};
 dispose(){if(this.disposed)return;this.disposed=true;cancelAnimationFrame(this.frame);this.gate.advance();this.observer.disconnect();this.canvas.removeEventListener('click',this.clicked);this.timer?.dispose();this.session?.dispose();this.canvas.remove();}
}
