import {GpuSession,GpuTimer} from '../gpu/device';
import {RevisionGate,encodePasses} from '../gpu/contracts';
import common from '../../shaders/gpu/ibl-common.wgsl?raw';
import atlasSource from '../../shaders/gpu/ibl-atlas.wgsl?raw';
import imageSource from '../../shaders/gpu/ibl-image.wgsl?raw';
import presentSource from '../../shaders/gpu/present.wgsl?raw';
import type {LightingState} from './state';
import type {LightingReport,LightingInspection} from './renderer';
import {integrateEnvironment} from './math';
export class IblWebGPURenderer {
 canvas=document.createElement('canvas');session!:GpuSession;timer!:GpuTimer;uniforms!:GPUBuffer;displayUniforms!:GPUBuffer;debug!:GPUBuffer;atlas!:GPUTexture;image!:GPUTexture;atlasPipeline!:GPUComputePipeline;imagePipeline!:GPUComputePipeline;inspectPipeline!:GPUComputePipeline;displayPipeline!:GPURenderPipeline;atlasGroup!:GPUBindGroup;imageGroup!:GPUBindGroup;displayGroup!:GPUBindGroup;
 state:LightingState;ready=false;pending=true;paused=false;visible=true;displayDirty=false;disposed=false;lost=false;frame=0;generation=0;referenceTimer=0;atlasKey='';atlasBuilds=0;inspection:LightingInspection|null=null;selected:[number,number]|null=null;gate=new RevisionGate();observer:IntersectionObserver;
 private constructor(public host:HTMLElement,s:LightingState,public report:(r:LightingReport)=>void){this.state=structuredClone(s);this.canvas.width=480;this.canvas.height=160;host.append(this.canvas);this.canvas.setAttribute('aria-label','WebGPU IBL：直接积分、预滤波与差值');this.canvas.addEventListener('click',this.clicked);this.observer=new IntersectionObserver(([e])=>{this.visible=e.isIntersecting;if(this.visible)this.request();else{cancelAnimationFrame(this.frame);this.frame=0;}});this.observer.observe(host);}
 static async create(host:HTMLElement,s:LightingState,report:(r:LightingReport)=>void){const e=new IblWebGPURenderer(host,s,report);try{await e.initialize();return e;}catch(error){e.dispose();throw error;}}
 private async initialize(){this.session=await GpuSession.create(this.canvas,error=>{this.lost=true;this.setPaused(true);this.cancelReference();this.gate.advance();this.report({ready:false,pending:false,error,inspection:null});});const d=this.session.device;this.timer=new GpuTimer(this.session);this.uniforms=this.session.buffer('IBL parameters',32,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.displayUniforms=this.session.buffer('IBL display',16,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.debug=this.session.buffer('IBL inspect 3 vec4',48,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC);this.atlas=this.session.texture('IBL prefilter atlas',448,32,'rgba16float',GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.TEXTURE_BINDING);this.image=this.session.texture('IBL image',480,160,'rgba32float',GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.TEXTURE_BINDING);
 const [a,m,display]=await Promise.all([this.session.shader(common+atlasSource,'IBL atlas'),this.session.shader(common+imageSource,'IBL integration'),this.session.shader(presentSource,'IBL display')]);
 this.atlasPipeline=await d.createComputePipelineAsync({layout:'auto',compute:{module:a,entryPoint:'main'}});this.atlasGroup=d.createBindGroup({layout:this.atlasPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniforms}},{binding:1,resource:this.atlas.createView()}]});
 const layout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.COMPUTE,buffer:{type:'uniform'}},{binding:1,visibility:GPUShaderStage.COMPUTE,texture:{sampleType:'unfilterable-float'}},{binding:2,visibility:GPUShaderStage.COMPUTE,storageTexture:{format:'rgba32float',access:'write-only'}},{binding:3,visibility:GPUShaderStage.COMPUTE,buffer:{type:'storage'}}]});const pl=d.createPipelineLayout({bindGroupLayouts:[layout]});this.imagePipeline=await d.createComputePipelineAsync({layout:pl,compute:{module:m,entryPoint:'render'}});this.inspectPipeline=await d.createComputePipelineAsync({layout:pl,compute:{module:m,entryPoint:'inspect'}});this.imageGroup=d.createBindGroup({layout,entries:[{binding:0,resource:{buffer:this.uniforms}},{binding:1,resource:this.atlas.createView()},{binding:2,resource:this.image.createView()},{binding:3,resource:{buffer:this.debug}}]});
 const dl=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'unfilterable-float'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}}]});this.displayPipeline=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[dl]}),vertex:{module:display,entryPoint:'vertex'},fragment:{module:display,entryPoint:'fragment',targets:[{format:this.session.format}]},primitive:{topology:'triangle-list'}});this.displayGroup=d.createBindGroup({layout:dl,entries:[{binding:0,resource:this.image.createView()},{binding:1,resource:{buffer:this.displayUniforms}}]});const info=this.session.adapter;this.report({device:`WebGPU · ${info.vendor} / ${info.architecture} · ${info.fallback?'软件适配器':'非软件回退'}`,state:this.state});this.write();this.request();}
 private write(){if(!this.uniforms)return;this.session.device.queue.writeBuffer(this.uniforms,0,new Float32Array([this.state.roughness,this.state.rotation,+this.state.diffuse,this.state.environment,...(this.selected??[.5,.5]),0,0]));this.session.device.queue.writeBuffer(this.displayUniforms,0,new Float32Array([480,160,this.state.exposure,3]));}
 update(s:LightingState){if(this.disposed)return;const onlyExposure=this.ready&&JSON.stringify({...this.state,exposure:0})===JSON.stringify({...s,exposure:0});this.state=structuredClone(s);this.write();if(onlyExposure){this.report({state:this.state});if(!this.pending)this.present();return;}this.cancelReference();this.gate.advance();this.inspection=null;this.pending=true;this.report({state:this.state,pending:true,inspection:null,gpuMs:null});this.request();}
 private request(){if(!this.imagePipeline||this.disposed||this.lost||(this.paused&&this.pending)||!this.visible||(!this.pending&&!this.displayDirty)||this.frame)return;this.frame=requestAnimationFrame(()=>{this.frame=0;if(this.pending)this.render();else this.present();});}
 setPaused(value:boolean){this.paused=value;cancelAnimationFrame(this.frame);this.frame=0;this.report({paused:value});if(!value)this.request();}
 step(){if(!this.disposed&&!this.lost&&this.imagePipeline)this.render();}
 private presentPass(cmd:GPUCommandEncoder){const p=cmd.beginRenderPass({colorAttachments:[{view:this.session.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});p.setPipeline(this.displayPipeline);p.setBindGroup(0,this.displayGroup);p.draw(3);p.end();}
 private present(){if(this.disposed||this.lost)return;if(!this.visible){this.displayDirty=true;return;}this.displayDirty=false;const cmd=this.session.device.createCommandEncoder();this.presentPass(cmd);this.session.device.queue.submit([cmd.finish()]);}
 private render(){const start=performance.now(),cmd=this.session.device.createCommandEncoder(),key=JSON.stringify([this.state.environment,this.state.rotation]);this.write();if(key!==this.atlasKey){const p=cmd.beginComputePass();p.setPipeline(this.atlasPipeline);p.setBindGroup(0,this.atlasGroup);p.dispatchWorkgroups(56,4);p.end();this.atlasKey=key;this.atlasBuilds++;}let timed=false;const token=JSON.stringify(this.state);
 encodePasses(cmd,[{name:'environment integral',reads:['atlas','parameters'],writes:['linear'],encode:e=>{const p=e.beginComputePass({timestampWrites:this.timer.writes()});p.setPipeline(this.imagePipeline);p.setBindGroup(0,this.imageGroup);p.dispatchWorkgroups(60,20);p.end();timed=this.timer.resolve(e);}},{name:'display',reads:['linear'],writes:['canvas'],encode:e=>this.presentPass(e)}],['atlas','parameters']);this.session.device.queue.submit([cmd.finish()]);this.ready=true;this.displayDirty=false;this.pending=false;this.report({ready:true,pending:false,cpuMs:performance.now()-start,atlasBuilds:this.atlasBuilds});if(timed)this.timer.read().then(gpuMs=>{if(!this.disposed&&token===JSON.stringify(this.state))this.report({gpuMs});}).catch(()=>{});if(this.selected)void this.pick(...this.selected);}
 async pick(u=.5,v=.5){if(!this.ready||this.pending||this.lost)return;this.cancelReference();const uv:[number,number]=[(Math.min(159,Math.max(0,Math.floor(u*160)))+.5)/160,(Math.min(159,Math.max(0,Math.floor(v*160)))+.5)/160];this.selected=uv;this.inspection=null;this.report({inspection:null});const token=this.gate.advance();this.write();const cmd=this.session.device.createCommandEncoder(),p=cmd.beginComputePass();p.setPipeline(this.inspectPipeline);p.setBindGroup(0,this.imageGroup);p.dispatchWorkgroups(1);p.end();this.session.device.queue.submit([cmd.finish()]);try{const data=new Float32Array(await this.session.readBuffer(this.debug,48));if(this.disposed||!this.gate.accepts(token))return;const inspection:LightingInspection={uv,gpu:[0,1,2].map(i=>Array.from(data.slice(i*4,i*4+3)))};const x=(uv[0]-.5)*2.4,y=(uv[1]-.5)*2.4,z=1-x*x-y*y;if(z>0)inspection.normal=[x,y,Math.sqrt(z)];this.inspection=inspection;this.report({inspection});}catch(e){if(!this.disposed&&this.gate.accepts(token))this.report({error:'WebGPU 检查失败：'+String(e),inspection:null});}}
 generateReference(){if(!this.inspection?.normal||this.pending)return;const token=++this.generation,state=structuredClone(this.state),inspection=this.inspection,n=inspection.normal!;clearTimeout(this.referenceTimer);this.report({referenceRunning:true});this.referenceTimer=window.setTimeout(()=>{const low=integrateEnvironment(n,state.roughness,state.environment,state.rotation,state.diffuse,32768),high=integrateEnvironment(n,state.roughness,state.environment,state.rotation,state.diffuse,65536);if(this.disposed||token!==this.generation)return;inspection.reference={low,high,convergence:Math.max(...high.map((v,i)=>Math.abs(v-low[i]))),error:Math.max(...high.map((v,i)=>Math.abs(v-inspection.gpu[0][i])))};this.report({inspection:{...inspection},referenceRunning:false});},30);}
 cancelReference(){clearTimeout(this.referenceTimer);this.generation++;this.report({referenceRunning:false});}
 private clicked=(e:MouseEvent)=>{const b=this.canvas.getBoundingClientRect();void this.pick(((e.clientX-b.left)/b.width*3)%1,1-(e.clientY-b.top)/b.height);};
 dispose(){if(this.disposed)return;this.disposed=true;cancelAnimationFrame(this.frame);clearTimeout(this.referenceTimer);this.generation++;this.gate.advance();this.observer.disconnect();this.canvas.removeEventListener('click',this.clicked);this.timer?.dispose();this.session?.dispose();this.canvas.remove();}
}
