import {PerspectiveCamera,OrthographicCamera,WebGPUCoordinateSystem,Matrix4} from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GpuSession,GpuTimer} from './device';
import {createGallery} from './gallery-scene';
import {qualityProfiles,type Quality} from './contracts';
import source from '../../shaders/gpu/csm.wgsl?raw';
import depthSource from '../../shaders/gpu/csm-depth.wgsl?raw';
import {fitCascades,cascadeBlend,defaultCsmState,type CsmState} from './csm';
import present from '../../shaders/gpu/present.wgsl?raw';
export class CsmRenderer {
 canvas=document.createElement('canvas');session!:GpuSession;timer!:GpuTimer;camera=new PerspectiveCamera(43,16/9,.1,80);light=new OrthographicCamera(-9,9,9,-9,.1,30);controls:OrbitControls;snapshot=createGallery();vertices!:GPUBuffer;uniforms!:GPUBuffer;displayUniforms!:GPUBuffer;shadows:GPUTexture[]=[];lightUniforms:GPUBuffer[]=[];shadowGroups:GPUBindGroup[]=[];diagnostic!:GPUTexture;state:CsmState=defaultCsmState();revision=0;readSerial=0;inspection:Record<string,unknown>|null=null;depth!:GPUTexture;image!:GPUTexture;shadowPipeline!:GPURenderPipeline;mainPipeline!:GPURenderPipeline;displayPipeline!:GPURenderPipeline;mainGroup!:GPUBindGroup;displayGroup!:GPUBindGroup;frame=0;disposed=false;visible=true;paused=false;ready=false;dirty=true;observer:IntersectionObserver;pointer=[0,0];width:number;height:number;
 constructor(public host:HTMLElement,public report:(r:Record<string,unknown>)=>void,public quality:Quality='standard'){const profile=qualityProfiles[quality];this.width=quality==='low'?Math.max(160,Math.min(profile.width,Math.round(host.clientWidth*(window.devicePixelRatio||1)))):profile.width;this.height=Math.round(this.width*9/16);this.canvas.width=this.width;this.canvas.height=this.height;host.append(this.canvas);this.canvas.addEventListener('pointerdown',this.down);this.canvas.addEventListener('pointerup',this.up);this.camera.coordinateSystem=WebGPUCoordinateSystem;this.camera.updateProjectionMatrix();this.controls=new OrbitControls(this.camera,this.canvas);this.controls.minDistance=5;this.controls.maxDistance=22;this.controls.maxPolarAngle=Math.PI*.48;this.reset();this.controls.addEventListener('change',this.changed);this.observer=new IntersectionObserver(([e])=>{this.visible=e.isIntersecting;if(this.visible)this.request();else{cancelAnimationFrame(this.frame);this.frame=0;}});this.observer.observe(host);}
 static async create(host:HTMLElement,report:(r:Record<string,unknown>)=>void,quality:Quality='standard'){const e=new CsmRenderer(host,report,quality);try{await e.initialize();return e;}catch(error){e.dispose();throw error;}}
 async initialize(){this.session=await GpuSession.create(this.canvas,error=>{this.ready=false;cancelAnimationFrame(this.frame);this.frame=0;this.report({error,ready:false});},this.quality);this.timer=new GpuTimer(this.session);const d=this.session.device;this.vertices=this.session.buffer('gallery vertices',this.snapshot.vertices.byteLength,GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST);d.queue.writeBuffer(this.vertices,0,this.snapshot.vertices);this.uniforms=this.session.buffer('csm matrices',464,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.displayUniforms=this.session.buffer('gallery display',16,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);const shadowSize=this.quality==='low'?1024:2048;this.shadows=[0,1,2,3].map(i=>this.session.texture('cascade '+i,shadowSize,shadowSize,'depth32float',GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING));this.lightUniforms=[0,1,2,3].map(i=>this.session.buffer('cascade matrix '+i,64,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST));this.diagnostic=this.session.texture('cascade diagnostic',this.width,this.height,'rgba32float',GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC);this.depth=this.session.texture('gallery depth',this.width,this.height,'depth32float',GPUTextureUsage.RENDER_ATTACHMENT);this.image=this.session.texture('gallery HDR',this.width,this.height,'rgba16float',GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING);const [shader,display,depth]=await Promise.all([this.session.shader(source,'gallery'),this.session.shader(present,'gallery display'),this.session.shader(depthSource,'CSM depth')]);const layout:GPUVertexBufferLayout={arrayStride:64,attributes:[0,1,2,3].map(i=>({shaderLocation:i,offset:i*16,format:'float32x4' as const}))};
 this.shadowPipeline=await d.createRenderPipelineAsync({layout:'auto',vertex:{module:depth,entryPoint:'vertex',buffers:[layout]},primitive:{topology:'triangle-list',cullMode:'back'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less'}});this.shadowGroups=this.lightUniforms.map(buffer=>d.createBindGroup({layout:this.shadowPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer}}]}));this.mainPipeline=await d.createRenderPipelineAsync({layout:'auto',vertex:{module:shader,entryPoint:'vertex',buffers:[layout]},fragment:{module:shader,entryPoint:'fragment',targets:[{format:'rgba16float'},{format:'rgba32float'}]},primitive:{topology:'triangle-list',cullMode:'back'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less'}});this.mainGroup=d.createBindGroup({layout:this.mainPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniforms}},...this.shadows.map((t,i)=>({binding:i+1,resource:t.createView()})),{binding:5,resource:d.createSampler({compare:'less-equal',magFilter:'linear',minFilter:'linear'})}]});this.displayPipeline=await d.createRenderPipelineAsync({layout:'auto',vertex:{module:display,entryPoint:'vertex'},fragment:{module:display,entryPoint:'fragment',targets:[{format:this.session.format}]},primitive:{topology:'triangle-list'}});this.displayGroup=d.createBindGroup({layout:this.displayPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:this.image.createView()},{binding:1,resource:{buffer:this.displayUniforms}}]});this.light.coordinateSystem=WebGPUCoordinateSystem;this.light.position.set(4,9,5);this.light.lookAt(0,0,0);this.light.updateProjectionMatrix();this.light.updateMatrixWorld();this.ready=true;this.report({ready:true,width:this.width,height:this.height,quality:this.quality,adapter:this.session.adapter,objects:this.snapshot.objects.length,triangles:this.snapshot.vertices.length/48,resources:this.session.budget.snapshot()});this.request();}
 update(state:CsmState){if(state.quality!==this.quality)throw Error('质量档变化需重新初始化');this.state=structuredClone(state);this.camera.position.set(...state.camera.position);this.controls.target.set(...state.camera.target);this.camera.lookAt(this.controls.target);this.controls.update();this.changed();}
 reset(){this.update({...defaultCsmState(),quality:this.quality});}
 exportState(){return {...structuredClone(this.state),camera:{position:this.camera.position.toArray() as [number,number,number],target:this.controls.target.toArray() as [number,number,number]}};}
 private changed=()=>{this.revision++;this.inspection=null;this.report({inspection:null,state:this.exportState(),pending:true,gpuMs:null});this.dirty=true;this.request();};private request(){if(!this.ready||this.paused||!this.visible||!this.dirty||this.frame||this.disposed)return;this.frame=requestAnimationFrame(()=>{this.frame=0;this.render();});}
 setPaused(value:boolean){this.paused=value;cancelAnimationFrame(this.frame);this.frame=0;this.report({paused:value});if(!value)this.request();}
 step(){if(this.ready&&!this.disposed){cancelAnimationFrame(this.frame);this.frame=0;this.render();}}
 render(){const start=performance.now(),renderRevision=this.revision;this.camera.updateMatrixWorld();const fit=fitCascades(this.camera,this.state.lambda,this.state.stable,this.quality==='low'?1024:2048),data=new Float32Array(116);data.set(new Matrix4().multiplyMatrices(this.camera.projectionMatrix,this.camera.matrixWorldInverse).elements);data.set(this.camera.matrixWorldInverse.elements,16);fit.cascades.forEach((c,i)=>data.set(c.matrix.elements,32+i*16));data.set(fit.splits,96);data.set([...this.camera.position.toArray(),1],100);data.set([4,9,5,0],104);data.set([this.state.lambda,+this.state.blend,+this.state.debug,0],108);data.set(fit.cascades.map(c=>c.texel),112);const d=this.session.device;d.queue.writeBuffer(this.uniforms,0,data);d.queue.writeBuffer(this.displayUniforms,0,new Float32Array([this.width,this.height,.25,3]));const cmd=d.createCommandEncoder();for(let i=0;i<4;i++){d.queue.writeBuffer(this.lightUniforms[i],0,new Float32Array(fit.cascades[i].matrix.elements));const pass=cmd.beginRenderPass({colorAttachments:[],depthStencilAttachment:{view:this.shadows[i].createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1}});pass.setPipeline(this.shadowPipeline);pass.setBindGroup(0,this.shadowGroups[i]);pass.setVertexBuffer(0,this.vertices);pass.draw(this.snapshot.vertices.length/16);pass.end();}const pass=cmd.beginRenderPass({timestampWrites:this.timer.writes(),colorAttachments:[{view:this.image.createView(),loadOp:'clear',storeOp:'store',clearValue:[.12,.19,.22,1]},{view:this.diagnostic.createView(),loadOp:'clear',storeOp:'store',clearValue:[0,-1,0,0]}],depthStencilAttachment:{view:this.depth.createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1}});pass.setPipeline(this.mainPipeline);pass.setBindGroup(0,this.mainGroup);pass.setVertexBuffer(0,this.vertices);pass.draw(this.snapshot.vertices.length/16);pass.end();const timed=this.timer.resolve(cmd);const screen=cmd.beginRenderPass({colorAttachments:[{view:this.session.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});screen.setPipeline(this.displayPipeline);screen.setBindGroup(0,this.displayGroup);screen.draw(3);screen.end();d.queue.submit([cmd.finish()]);this.dirty=false;this.report({pending:false,cpuMs:performance.now()-start,splits:fit.splits,cascades:fit.cascades.map(c=>({near:c.near,far:c.far,radius:c.radius,texel:c.texel}))});if(timed)this.timer.read().then(gpuMs=>{if(!this.disposed&&renderRevision===this.revision)this.report({gpuMs});}).catch(()=>{});}
 private down=(e:PointerEvent)=>{this.pointer=[e.clientX,e.clientY];};private up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-this.pointer[0],e.clientY-this.pointer[1])>5)return;const b=this.canvas.getBoundingClientRect();void this.inspect((e.clientX-b.left)/b.width,(e.clientY-b.top)/b.height);};
 async inspect(u=.5,v=.5){if(!this.ready||this.dirty||!Number.isFinite(u)||!Number.isFinite(v))return;this.inspection=null;this.report({inspection:null});const request=++this.readSerial;const token=this.revision,buffer=this.session.buffer('CSM pixel readback',256,GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ);try{const cmd=this.session.device.createCommandEncoder();cmd.copyTextureToBuffer({texture:this.diagnostic,origin:[Math.min(this.width-1,Math.max(0,Math.floor(u*this.width))),Math.min(this.height-1,Math.max(0,Math.floor(v*this.height)))]},{buffer,bytesPerRow:256},[1,1]);this.session.device.queue.submit([cmd.finish()]);await buffer.mapAsync(GPUMapMode.READ);const values=Array.from(new Float32Array(buffer.getMappedRange().slice(0,16)));if(this.disposed||token!==this.revision||request!==this.readSerial)return;const split=fitCascades(this.camera,this.state.lambda,this.state.stable,this.quality==='low'?1024:2048).splits;const expected=cascadeBlend(values[0],split,this.camera.near,this.state.blend);this.inspection={uv:[u,v],depth:values[0],cascade:values[1],blend:values[2],visibility:values[3],expected,valid:values[1]>=0};this.report({inspection:this.inspection});}finally{this.session.release(buffer);}}
 dispose(){this.disposed=true;this.revision++;this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointerup',this.up);cancelAnimationFrame(this.frame);this.controls.dispose();this.observer.disconnect();this.timer?.dispose();this.session?.dispose();this.canvas.remove();}
}
