import {Matrix4,OrthographicCamera,PerspectiveCamera,Vector3,WebGPUCoordinateSystem} from 'three';
export function cascadeSplits(near:number,far:number,lambda:number){if(!(near>0&&far>near&&lambda>=0&&lambda<=1))throw Error('非法级联范围');return Array.from({length:4},(_,i)=>{const t=(i+1)/4;return (1-lambda)*(near+(far-near)*t)+lambda*near*(far/near)**t;});}
export function selectCascade(depth:number,splits:number[]){return Math.min(3,Math.max(0,splits.findIndex(s=>depth<=s)===-1?3:splits.findIndex(s=>depth<=s)));}
export function cascadeBlend(depth:number,splits:number[],near:number,enabled=true){const level=selectCascade(depth,splits);if(!enabled||level===3)return {level,weight:0};const start=level===0?near:splits[level-1],end=splits[level],width=(end-start)*.1;const t=Math.max(0,Math.min(1,(depth-(end-width))/width));return {level,weight:t*t*(3-2*t)};}
export function frustumCorners(camera:PerspectiveCamera,near:number,far:number){camera.updateMatrixWorld();const origin=camera.position,right=new Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new Vector3().setFromMatrixColumn(camera.matrixWorld,1),forward=new Vector3().setFromMatrixColumn(camera.matrixWorld,2).negate(),tan=Math.tan(camera.fov*Math.PI/360);const corners:Vector3[]=[];for(const z of [near,far])for(const y of [-1,1])for(const x of [-1,1])corners.push(origin.clone().addScaledVector(forward,z).addScaledVector(right,x*z*tan*camera.aspect).addScaledVector(up,y*z*tan));return corners;}
export function fitCascades(camera:PerspectiveCamera,lambda:number,stable:boolean,resolution:number){const splits=cascadeSplits(camera.near,camera.far,lambda),sun=new Vector3(4,9,5).normalize(),right=new Vector3(0,1,0).cross(sun).normalize(),up=sun.clone().cross(right).normalize();return {splits,cascades:splits.map((far,i)=>{let near=i===0?camera.near:splits[i-1];if(i>0){const prior=i===1?camera.near:splits[i-2];near-=.1*(near-prior);}const corners=frustumCorners(camera,near,far),center=corners.reduce((a,b)=>a.add(b),new Vector3()).multiplyScalar(1/8);const base=Math.ceil(Math.max(...corners.map(p=>p.distanceTo(center)))*16)/16;const radius=base/(1-2/resolution),texel=2*radius/resolution;const cx=center.dot(right),cy=center.dot(up),cz=center.dot(sun);if(stable)center.copy(right).multiplyScalar(Math.round(cx/texel)*texel).addScaledVector(up,Math.round(cy/texel)*texel).addScaledVector(sun,cz);const light=new OrthographicCamera(-radius,radius,radius,-radius,.1,200);light.coordinateSystem=WebGPUCoordinateSystem;light.position.copy(center).addScaledVector(sun,100);light.lookAt(center);light.updateProjectionMatrix();light.updateMatrixWorld();const matrix=new Matrix4().multiplyMatrices(light.projectionMatrix,light.matrixWorldInverse);return {near,far,radius,texel,matrix,corners,center};})};}
export interface CsmState {version:2;sceneId:'gallery';sceneRevision:1;seed:0;frame:0;quality:'low'|'standard'|'high';lambda:number;stable:boolean;blend:boolean;debug:boolean;task:number;camera:{position:[number,number,number];target:[number,number,number]}}
export const defaultCsmState=():CsmState=>({version:2,sceneId:'gallery',sceneRevision:1,seed:0,frame:0,quality:'standard',lambda:.6,stable:true,blend:true,debug:false,task:0,camera:{position:[8.5,6.8,10],target:[0,1.4,-.6]}});
export const csmHash=(s:CsmState)=>'#csm='+encodeURIComponent(JSON.stringify(s));
export function decodeCsm(hash:string):{state:CsmState;notice?:string}{const fallback={state:defaultCsmState(),notice:'链接无效或版本不兼容，已恢复默认。'};if(!hash.startsWith('#csm='))return {state:defaultCsmState()};try{if(hash.length>4000)throw 0;const s=JSON.parse(decodeURIComponent(hash.slice(5)));if(s.version!==2||s.sceneId!=='gallery'||s.sceneRevision!==1||s.seed!==0||s.frame!==0||!['low','standard','high'].includes(s.quality)||!Number.isFinite(s.lambda)||s.lambda<0||s.lambda>1||![0,1,2].includes(s.task)||!['stable','blend','debug'].every(k=>typeof s[k]==='boolean'))throw 0;for(const v of [s.camera?.position,s.camera?.target])if(!Array.isArray(v)||v.length!==3||!v.every(x=>Number.isFinite(x)&&Math.abs(x)<=40))throw 0;const length=Math.hypot(...s.camera.position.map((x:number,i:number)=>x-s.camera.target[i]));if(length<5||length>22)throw 0;return {state:s as CsmState};}catch{return fallback;}}
