import {PerspectiveCamera,OrthographicCamera,WebGPUCoordinateSystem,Matrix4} from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GpuSession,GpuTimer} from './device';
import {createGallery} from './gallery-scene';
import {qualityProfiles,type Quality} from './contracts';
import source from '../../shaders/gpu/gallery.wgsl?raw';
import present from '../../shaders/gpu/present.wgsl?raw';
export class GalleryRenderer {
 canvas=document.createElement('canvas');session!:GpuSession;timer!:GpuTimer;camera=new PerspectiveCamera(43,16/9,.1,80);light=new OrthographicCamera(-9,9,9,-9,.1,30);controls:OrbitControls;snapshot=createGallery();vertices!:GPUBuffer;uniforms!:GPUBuffer;displayUniforms!:GPUBuffer;shadow!:GPUTexture;depth!:GPUTexture;image!:GPUTexture;shadowPipeline!:GPURenderPipeline;mainPipeline!:GPURenderPipeline;displayPipeline!:GPURenderPipeline;shadowGroup!:GPUBindGroup;mainGroup!:GPUBindGroup;displayGroup!:GPUBindGroup;postProcess:((encoder:GPUCommandEncoder)=>void)|null=null;frame=0;renderGeneration=0;disposed=false;visible=true;paused=false;ready=false;dirty=true;observer:IntersectionObserver;width:number;height:number;
 constructor(public host:HTMLElement,public report:(r:Record<string,unknown>)=>void,public quality:Quality='standard'){const profile=qualityProfiles[quality];this.width=quality==='low'?Math.max(160,Math.min(profile.width,Math.round(host.clientWidth*(window.devicePixelRatio||1)))):profile.width;this.height=Math.round(this.width*9/16);this.canvas.width=this.width;this.canvas.height=this.height;host.append(this.canvas);this.camera.coordinateSystem=WebGPUCoordinateSystem;this.camera.updateProjectionMatrix();this.controls=new OrbitControls(this.camera,this.canvas);this.controls.minDistance=5;this.controls.maxDistance=22;this.controls.maxPolarAngle=Math.PI*.48;this.reset();this.controls.addEventListener('change',this.changed);this.observer=new IntersectionObserver(([e])=>{this.visible=e.isIntersecting;if(this.visible)this.request();else{cancelAnimationFrame(this.frame);this.frame=0;}});this.observer.observe(host);}
 static async create(host:HTMLElement,report:(r:Record<string,unknown>)=>void){const e=new GalleryRenderer(host,report,matchMedia('(max-width:700px)').matches?'low':'standard');try{await e.initialize();return e;}catch(error){e.dispose();throw error;}}
 async initialize(){this.session=await GpuSession.create(this.canvas,error=>{this.ready=false;cancelAnimationFrame(this.frame);this.frame=0;this.report({error,ready:false});},this.quality);this.timer=new GpuTimer(this.session);const d=this.session.device;this.vertices=this.session.buffer('gallery vertices',this.snapshot.vertices.byteLength,GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST);d.queue.writeBuffer(this.vertices,0,this.snapshot.vertices);this.uniforms=this.session.buffer('gallery camera',160,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.displayUniforms=this.session.buffer('gallery display',16,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);const shadowSize=this.quality==='low'?1024:2048;this.shadow=this.session.texture('gallery shadow',shadowSize,shadowSize,'depth32float',GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING);this.depth=this.session.texture('gallery depth',this.width,this.height,'depth32float',GPUTextureUsage.RENDER_ATTACHMENT);this.image=this.session.texture('gallery HDR',this.width,this.height,'rgba16float',GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_SRC);const [shader,display]=await Promise.all([this.session.shader(source,'gallery'),this.session.shader(present,'gallery display')]);const layout:GPUVertexBufferLayout={arrayStride:64,attributes:[0,1,2,3].map(i=>({shaderLocation:i,offset:i*16,format:'float32x4' as const}))};
 this.shadowPipeline=await d.createRenderPipelineAsync({layout:'auto',vertex:{module:shader,entryPoint:'depthVertex',buffers:[layout]},primitive:{topology:'triangle-list',cullMode:'back'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less'}});this.shadowGroup=d.createBindGroup({layout:this.shadowPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniforms}}]});this.mainPipeline=await d.createRenderPipelineAsync({layout:'auto',vertex:{module:shader,entryPoint:'vertex',buffers:[layout]},fragment:{module:shader,entryPoint:'fragment',targets:[{format:'rgba16float'}]},primitive:{topology:'triangle-list',cullMode:'back'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less'}});this.mainGroup=d.createBindGroup({layout:this.mainPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniforms}},{binding:1,resource:this.shadow.createView()},{binding:2,resource:d.createSampler({compare:'less-equal',magFilter:'linear',minFilter:'linear'})}]});this.displayPipeline=await d.createRenderPipelineAsync({layout:'auto',vertex:{module:display,entryPoint:'vertex'},fragment:{module:display,entryPoint:'fragment',targets:[{format:this.session.format}]},primitive:{topology:'triangle-list'}});this.displayGroup=d.createBindGroup({layout:this.displayPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:this.image.createView()},{binding:1,resource:{buffer:this.displayUniforms}}]});this.light.coordinateSystem=WebGPUCoordinateSystem;this.light.position.set(4,9,5);this.light.lookAt(0,0,0);this.light.updateProjectionMatrix();this.light.updateMatrixWorld();this.ready=true;this.report({ready:true,width:this.width,height:this.height,quality:this.quality,adapter:this.session.adapter,objects:this.snapshot.objects.length,triangles:this.snapshot.vertices.length/48,resources:this.session.budget.snapshot()});this.request();}
 reset(){this.camera.position.set(...this.snapshot.camera.position);this.controls.target.set(...this.snapshot.camera.target);this.camera.lookAt(this.controls.target);this.controls.update();this.changed();}
 private changed=()=>{this.renderGeneration++;this.report({gpuMs:null});this.dirty=true;this.request();};private request(){if(!this.ready||this.paused||!this.visible||!this.dirty||this.frame||this.disposed)return;this.frame=requestAnimationFrame(()=>{this.frame=0;this.render();});}
 setPaused(value:boolean){this.paused=value;cancelAnimationFrame(this.frame);this.frame=0;this.report({paused:value});if(!value)this.request();}
 step(){if(this.ready&&!this.disposed){cancelAnimationFrame(this.frame);this.frame=0;this.render();}}
 render(){const start=performance.now(),renderGeneration=this.renderGeneration;this.camera.updateMatrixWorld();const data=new Float32Array(40);data.set(new Matrix4().multiplyMatrices(this.camera.projectionMatrix,this.camera.matrixWorldInverse).elements);data.set(new Matrix4().multiplyMatrices(this.light.projectionMatrix,this.light.matrixWorldInverse).elements,16);data.set([...this.camera.position.toArray(),1],32);data.set([4,9,5,0],36);const d=this.session.device;d.queue.writeBuffer(this.uniforms,0,data);d.queue.writeBuffer(this.displayUniforms,0,new Float32Array([this.width,this.height,.25,3]));const cmd=d.createCommandEncoder();const shadow=cmd.beginRenderPass({colorAttachments:[],depthStencilAttachment:{view:this.shadow.createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1}});shadow.setPipeline(this.shadowPipeline);shadow.setBindGroup(0,this.shadowGroup);shadow.setVertexBuffer(0,this.vertices);shadow.draw(this.snapshot.vertices.length/16);shadow.end();const pass=cmd.beginRenderPass({timestampWrites:this.timer.writes(),colorAttachments:[{view:this.image.createView(),loadOp:'clear',storeOp:'store',clearValue:[.12,.19,.22,1]}],depthStencilAttachment:{view:this.depth.createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1}});pass.setPipeline(this.mainPipeline);pass.setBindGroup(0,this.mainGroup);pass.setVertexBuffer(0,this.vertices);pass.draw(this.snapshot.vertices.length/16);pass.end();const timed=this.timer.resolve(cmd);this.postProcess?.(cmd);const screen=cmd.beginRenderPass({colorAttachments:[{view:this.session.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});screen.setPipeline(this.displayPipeline);screen.setBindGroup(0,this.displayGroup);screen.draw(3);screen.end();d.queue.submit([cmd.finish()]);this.dirty=false;this.report({cpuMs:performance.now()-start});if(timed)this.timer.read().then(gpuMs=>{if(!this.disposed&&renderGeneration===this.renderGeneration)this.report({gpuMs});}).catch(()=>{});}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.controls.dispose();this.observer.disconnect();this.timer?.dispose();this.session?.dispose();this.canvas.remove();}
}
