import {Vector3} from 'three';
import {GpuTimer} from './device';
import {GalleryRenderer} from './gallery-renderer';
import {defaultHdrState,hdrCombine,halfToFloat,type HdrState} from './hdr';
import source from '../../shaders/gpu/hdr.wgsl?raw';
export class HdrRenderer extends GalleryRenderer {
 state:HdrState=defaultHdrState();postReady=false;postTimer!:GpuTimer;postTimed=false;params!:GPUBuffer;extracted!:GPUTexture;blurX!:GPUTexture;blurred!:GPUTexture;composite!:GPUTexture;pipelines:GPUComputePipeline[]=[];groups:GPUBindGroup[]=[];views:GPUBindGroup[]=[];revision=0;readSerial=0;inspection:Record<string,unknown>|null=null;postFrame=0;pointer=[0,0];applying=false;
 static async create(host:HTMLElement,report:(r:Record<string,unknown>)=>void,quality:HdrState['quality']='standard'){const e=new HdrRenderer(host,report,quality);try{await e.initialize();return e;}catch(error){e.dispose();throw error;}}
 async initialize(){const report=this.report;this.report=r=>report({...r,ready:false});await super.initialize();this.postTimer=new GpuTimer(this.session);this.state={...defaultHdrState(),quality:this.quality};const d=this.session.device,halfW=Math.ceil(this.width/2),halfH=Math.ceil(this.height/2),usage=GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_SRC;this.params=this.session.buffer('HDR settings',16,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.extracted=this.session.texture('HDR bright extraction',halfW,halfH,'rgba16float',usage);this.blurX=this.session.texture('HDR blur horizontal',halfW,halfH,'rgba16float',usage);this.blurred=this.session.texture('HDR blur vertical',halfW,halfH,'rgba16float',usage);this.composite=this.session.texture('HDR composite',this.width,this.height,'rgba16float',usage);const shader=await this.session.shader(source,'HDR pipeline');const layout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.COMPUTE,texture:{sampleType:'unfilterable-float'}},{binding:1,visibility:GPUShaderStage.COMPUTE,storageTexture:{format:'rgba16float',access:'write-only'}},{binding:2,visibility:GPUShaderStage.COMPUTE,buffer:{type:'uniform'}},{binding:3,visibility:GPUShaderStage.COMPUTE,texture:{sampleType:'unfilterable-float'}}]});const pl=d.createPipelineLayout({bindGroupLayouts:[layout]});this.pipelines=await Promise.all(['extract','horizontal','vertical','combine'].map(entryPoint=>d.createComputePipelineAsync({layout:pl,compute:{module:shader,entryPoint}})));const inputs=[this.image,this.extracted,this.blurX,this.blurred],outputs=[this.extracted,this.blurX,this.blurred,this.composite];this.groups=inputs.map((input,i)=>d.createBindGroup({layout,entries:[{binding:0,resource:input.createView()},{binding:1,resource:outputs[i].createView()},{binding:2,resource:{buffer:this.params}},{binding:3,resource:this.image.createView()}]}));this.views=[this.image,this.extracted,this.blurred,this.composite].map(t=>d.createBindGroup({layout:this.displayPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:t.createView()},{binding:1,resource:{buffer:this.displayUniforms}}]}));this.postProcess=encoder=>this.encodePost(encoder);this.controls.addEventListener('change',this.cameraChanged);this.canvas.addEventListener('pointerdown',this.down);this.canvas.addEventListener('pointerup',this.up);this.report=report;this.postReady=true;this.dirty=true;this.postFrame=requestAnimationFrame(()=>{this.postFrame=0;if(!this.disposed&&this.dirty)this.render();});this.report({ready:true,pending:true,state:this.exportState(),resources:this.session.budget.snapshot()});}
 render(){if(this.disposed||!this.ready)return;if(!this.postReady){this.dirty=true;return;}super.render();this.report({pending:false});this.readPostTiming();}
 exportState():HdrState{return {...structuredClone(this.state),camera:{position:this.camera.position.toArray() as [number,number,number],target:this.controls.target.toArray() as [number,number,number]}};}
 update(s:HdrState){cancelAnimationFrame(this.postFrame);this.postFrame=0;if(s.quality!==this.quality)throw Error('质量档变化需重新初始化');const cameraChanged=JSON.stringify(s.camera)!==JSON.stringify(this.exportState().camera);this.state=structuredClone(s);this.revision++;this.inspection=null;if(cameraChanged){this.applying=true;this.camera.position.set(...s.camera.position);this.controls.target.set(...s.camera.target);this.controls.update();this.applying=false;this.dirty=true;}this.report({state:this.exportState(),inspection:null,pending:true,bloomGpuMs:null});if(!this.visible||this.paused){this.dirty=true;return;}if(cameraChanged||this.dirty)this.render();else{cancelAnimationFrame(this.postFrame);this.postFrame=requestAnimationFrame(()=>{this.postFrame=0;this.postOnly();});}}
 setPaused(value:boolean){if(this.postFrame)this.dirty=true;cancelAnimationFrame(this.postFrame);this.postFrame=0;super.setPaused(value);}
 private encodePost(cmd:GPUCommandEncoder){this.session.device.queue.writeBuffer(this.params,0,new Float32Array([this.state.threshold,this.state.strength,this.state.exposure,+this.state.wrongOrder]));const stamps=this.postTimer.writes();for(let i=0;i<4;i++){const timestampWrites=stamps?(i===0?{querySet:stamps.querySet,beginningOfPassWriteIndex:0}:i===3?{querySet:stamps.querySet,endOfPassWriteIndex:1}:undefined):undefined;const p=cmd.beginComputePass({timestampWrites});p.setPipeline(this.pipelines[i]);p.setBindGroup(0,this.groups[i]);p.dispatchWorkgroups(Math.ceil((i===3?this.width:Math.ceil(this.width/2))/8),Math.ceil((i===3?this.height:Math.ceil(this.height/2))/8));p.end();}this.postTimed=this.postTimer.resolve(cmd);const index=['raw','extracted','blurred','composite'].indexOf(this.state.view);this.displayGroup=this.views[index];this.session.device.queue.writeBuffer(this.displayUniforms,0,new Float32Array([this.width,this.height,this.state.exposure,this.state.wrongOrder&&index===3?2:3]));}
 private postOnly(){if(this.disposed||!this.ready)return;if(this.dirty&&!this.paused&&this.visible){cancelAnimationFrame(this.frame);this.frame=0;this.render();return;}if(!this.visible||this.paused){this.dirty=true;return;}const start=performance.now(),cmd=this.session.device.createCommandEncoder();this.encodePost(cmd);const p=cmd.beginRenderPass({colorAttachments:[{view:this.session.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});p.setPipeline(this.displayPipeline);p.setBindGroup(0,this.displayGroup);p.draw(3);p.end();this.session.device.queue.submit([cmd.finish()]);this.report({pending:false,postCpuMs:performance.now()-start});this.readPostTiming();}
 private readPostTiming(){if(!this.postTimed)return;this.postTimed=false;const token=this.revision;this.postTimer.read().then(bloomGpuMs=>{if(!this.disposed&&token===this.revision)this.report({bloomGpuMs});}).catch(()=>{});}
 private cameraChanged=()=>{if(this.applying)return;this.revision++;this.inspection=null;this.report({state:this.exportState(),inspection:null,pending:true,bloomGpuMs:null});};
 private down=(e:PointerEvent)=>{this.pointer=[e.clientX,e.clientY];};private up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-this.pointer[0],e.clientY-this.pointer[1])>5)return;const b=this.canvas.getBoundingClientRect();void this.inspect((e.clientX-b.left)/b.width,(e.clientY-b.top)/b.height);};
 inspectLight(){this.camera.updateMatrixWorld();const p=new Vector3(0,4.425,.6).project(this.camera);if(Math.abs(p.x)>1||Math.abs(p.y)>1||p.z<0||p.z>1){this.report({inspection:null,notice:'灯带示例点已离屏，请恢复机位或自行选点。'});return;}this.report({notice:undefined});return this.inspect(p.x*.5+.5,.5-p.y*.5);}
 private async pixel(texture:GPUTexture,x:number,y:number){const buffer=this.session.buffer('HDR pixel',256,GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ);try{const cmd=this.session.device.createCommandEncoder();cmd.copyTextureToBuffer({texture,origin:[x,y]},{buffer,bytesPerRow:256},[1,1]);this.session.device.queue.submit([cmd.finish()]);await buffer.mapAsync(GPUMapMode.READ);return Array.from(new Uint16Array(buffer.getMappedRange().slice(0,8))).slice(0,3).map(halfToFloat);}finally{this.session.release(buffer);}}
 async inspect(u=.5,v=.5){if(!this.ready||this.dirty||this.postFrame||!Number.isFinite(u)||!Number.isFinite(v))return;this.inspection=null;this.report({inspection:null});const request=++this.readSerial;const token=this.revision,x=Math.min(this.width-1,Math.max(0,Math.floor(u*this.width))),y=Math.min(this.height-1,Math.max(0,Math.floor(v*this.height)));try{const [raw,bloom,output]=await Promise.all([this.pixel(this.image,x,y),this.pixel(this.blurred,Math.floor(x/2),Math.floor(y/2)),this.pixel(this.composite,x,y)]);if(this.disposed||token!==this.revision||request!==this.readSerial)return;const expected=hdrCombine(raw,bloom,this.state);this.inspection={uv:[u,v],raw,bloom,output,expected,error:Math.max(...expected.map((v,i)=>Math.abs(v-output[i]))),signal:this.state.wrongOrder?'已映射的反例输出':'线性合成输出'};this.report({inspection:this.inspection});}catch(error){if(!this.disposed)this.report({error:String(error)});}}
 dispose(){this.revision++;this.postTimer?.dispose();cancelAnimationFrame(this.postFrame);this.controls.removeEventListener('change',this.cameraChanged);this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointerup',this.up);super.dispose();}
}
