import {useEffect,useRef,useState} from 'react';
import {defaultLightingState,decodeLighting,lightingHash,lightingTask,type LightingKind,type LightingState} from '../../lib/lighting/state';
import type {TransparencyWebGPURenderer} from '../../lib/lighting/transparency-webgpu';
import type {IblWebGPURenderer} from '../../lib/lighting/webgpu-renderer';
import type {LightingReport} from '../../lib/lighting/renderer';
import ObservationGuide from '../reading/ObservationGuide';
import './lighting.css';
const tasks={ibl:[['环境方向','固定漫反射白球，只旋转环境。','表面收到的是半球各方向的入射光，不是把背景贴到球上。'],['粗糙度与预滤波','固定环境，粗糙度在 0.2 到 1 之间变化，观察预滤波层间插值。','粗糙度改变积分核；预滤波假设 N=V=R，不是一般视角下的精确积分。'],['近似与参考','窄亮区环境下选球面点，生成独立 CPU 积分，再切换常量环境核对。','区分近似误差、GPU 256 样本误差和 CPU 收敛差。']],transparency:[['顺序与交叉','交换提交顺序，看对象中心排序与逐像素排序参考在交叉处是否一致。','一个全局物体顺序无法解决各像素不同的前后关系。'],['权重与透过率','保持透明度，改变深度权重；交换提交顺序检查 WBOIT。','加权和与透过率乘积与顺序无关，但合成颜色一般不等于精确排序。'],['高不透明度反例','把 alpha 提到 0.95 或 1，看最近一层的颜色是否占主导。','WBOIT 的颜色平均可能保留后层颜色；更平滑不是更准确。']]};
const vec=(a:number[])=>(a.map(x=>Number.isFinite(x)?x.toFixed(5):'非法').join(' / '));
export default function LightingLab({kind,embedded=false}:{kind:LightingKind;embedded?:boolean}){
 const host=useRef<HTMLDivElement>(null),engine=useRef<TransparencyWebGPURenderer|IblWebGPURenderer|null>(null),current=useRef(defaultLightingState(kind)),reportRef=useRef<LightingReport>({});
 const [state,setState]=useState(()=>defaultLightingState(kind)),[report,setReport]=useState<LightingReport>({}),[retry,setRetry]=useState(0),[notice,setNotice]=useState('选任一画面内的同位置，三个方法同步检查。'),[link,setLink]=useState('');
 useEffect(()=>{let disposed=false;const parsed=retry?{state:current.current}:embedded?{state:defaultLightingState(kind)}:decodeLighting(location.hash,kind);current.current=parsed.state;setState(parsed.state);setReport({});if(parsed.notice)setNotice(parsed.notice);
 const receive=(patch:LightingReport)=>{reportRef.current={...reportRef.current,...patch};setReport(reportRef.current);if(patch.state){current.current=patch.state;setState(patch.state);}};reportRef.current={};
 Promise.resolve().then(async()=>{if(disposed||!host.current)return;try{if(kind==='ibl'){const {IblWebGPURenderer}=await import('../../lib/lighting/webgpu-renderer');if(disposed||!host.current)return;const created=await IblWebGPURenderer.create(host.current,parsed.state,receive);if(disposed){created.dispose();return;}engine.current=created;}else{const {TransparencyWebGPURenderer}=await import('../../lib/lighting/transparency-webgpu');if(disposed||!host.current)return;const created=await TransparencyWebGPURenderer.create(host.current,parsed.state,receive);if(disposed){created.dispose();return;}engine.current=created;}}catch(e){receive({error:String(e),ready:false});}}).catch(e=>{if(!disposed)receive({error:String(e)});});
 const restore=()=>{if(embedded)return;const next=decodeLighting(location.hash,kind);engine.current?.setPaused(false);engine.current?.update(next.state);setNotice(next.notice??'已从分享链接恢复参数。');};window.addEventListener('hashchange',restore);
 const ctx=(document as any).modelContext,controller=new AbortController();if(!embedded&&ctx?.registerTool)Promise.resolve(ctx.registerTool({name:'read_'+kind+'_experiment',description:'只读返回当前参数、实际GPU检查与独立CPU参考。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...reportRef.current,state:current.current})},{signal:controller.signal})).catch(()=>{});
 return()=>{disposed=true;controller.abort();window.removeEventListener('hashchange',restore);engine.current?.dispose();engine.current=null;};
 },[kind,retry]);
 const change=(patch:Partial<LightingState>)=>engine.current?.update({...current.current,...patch});const load=(task:number)=>{engine.current?.setPaused(false);engine.current?.update(lightingTask(kind,task));};
 async function share(){const href=new URL('/labs/'+kind+'/'+lightingHash(current.current),location.origin).href;setLink(href);try{await navigator.clipboard.writeText(href);setNotice('分享链接已复制。');}catch{setNotice('复制下方链接即可分享。');}}
 const labels=kind==='ibl'?['256 样本环境积分','预滤波近似','线性绝对差 ×4']:['对象中心顺序 / 可反转','逐像素排序参考','WBOIT · 双通道累积'];const task=tasks[kind][state.task],i=report.inspection;
 return <section className="lighting-lab" data-lighting={kind}><header><span className="eyebrow">{kind==='ibl'?'ENVIRONMENT INTEGRATION':'TRANSPARENCY COMPOSITING'} · 算法实验</span><h3>{kind==='ibl'?'让整个环境参与反射。':'交叉的透明面，谁应该先画？'}</h3><p>{kind==='ibl'?'程序化方向环境，无外部贴图。白 Lambert 或 F₀=0.04 的单散射 GGX 分开观察，不叠加成完整材质。':'三张不折射、无光照的有限平面。正交投影下每像素有不同深度；颜色全部在线性空间合成。'}</p></header>
 <div className="lighting-tasks">{tasks[kind].map((t,index)=><button key={t[0]} disabled={!report.ready} aria-pressed={state.task===index} onClick={()=>load(index)}>{index+1} · {t[0]}</button>)}</div>
 <ObservationGuide key={state.task} focus={kind==='ibl'?'球心、掠射区与三个方法的差异。':'平面交叉处和三层重叠区域。'} action={task[1]} evidence={task[2]} caution={kind==='ibl'?'差值是 GPU 有限样本之间的差，不是绝对真值；独立积分只验证选中点。':'三个平面的逐像素参考不是一般场景的通用 OIT 实现。'}/>
 <div className="lighting-labels">{labels.map(label=><span key={label}>{label}</span>)}</div><div className="lighting-viewport" ref={host}>{i&&!report.pending&&[0,1,2].map(panel=><span className="lighting-marker" key={panel} aria-hidden="true" style={{left:((i.uv[0]+panel)*100/3)+'%',top:((1-i.uv[1])*100)+'%'}}/>)}{!report.ready&&<div className="lighting-fallback"><strong>{report.error??'准备 '+'WebGPU'+' 实验…'}</strong><p>{kind==='ibl'?'静态步骤：固定法线与视线，对环境各方向的 BRDF × 余弦贡献积分，再与预滤波近似比较。':'静态步骤：累加颜色 × alpha × 权重，乘积保存剩余透过率，最后与背景合成。'}</p>{report.error&&<button onClick={()=>setRetry(n=>n+1)}>重试实验</button>}</div>}{report.pending&&report.ready&&<div className="lighting-pending">旧检查已失效；等待当前状态计算。暂停时可单步。</div>}</div>
 <p role="status" className="lighting-status">{report.error?'交互不可用，正文可读':report.ready?(report.pending?'等待计算':'WebGPU · 就绪'):'初始化中'} · {notice}</p>
 <div className="lighting-actions"><button disabled={!report.ready||report.pending} onClick={()=>engine.current?.pick(.5,.5)}>检查中心点</button><button disabled={!report.ready} onClick={()=>engine.current?.setPaused(!report.paused)}>{report.paused?'恢复更新':'暂停更新'}</button><button disabled={!report.ready} onClick={()=>engine.current?.step()}>单步计算</button><button disabled={!report.ready} onClick={()=>load(state.task)}>恢复当前任务</button><button onClick={share}>分享实验</button></div>
 <fieldset disabled={!report.ready} className="lighting-controls">{kind==='ibl'?<>
 <label>环境<select aria-label="IBL 环境" value={state.environment} onChange={e=>change({environment:+e.target.value})}><option value="0">常量白环境 · 验证</option><option value="1">宽亮区与冷色侧光</option><option value="2">窄亮区 · 反例</option></select></label>
 <label>环境旋转 <output>{state.rotation}°</output><input aria-label="IBL 环境旋转" type="range" min="-180" max="180" value={state.rotation} onChange={e=>change({rotation:+e.target.value})}/></label>
 <label>粗糙度 <output>{state.roughness.toFixed(2)}</output><input aria-label="IBL 粗糙度" disabled={state.diffuse} type="range" min=".2" max="1" step=".01" value={state.roughness} onChange={e=>change({roughness:+e.target.value})}/></label>
 <label>信号<select aria-label="IBL 信号" value={state.diffuse?'diffuse':'specular'} onChange={e=>change({diffuse:e.target.value==='diffuse'})}><option value="diffuse">白 Lambert · E/π</option><option value="specular">GGX 镜面 · F₀=0.04</option></select></label>
 <label>曝光 <output>{state.exposure} EV</output><input aria-label="IBL 曝光" type="range" min="-3" max="3" step=".25" value={state.exposure} onChange={e=>change({exposure:+e.target.value})}/></label>
 </>:<>
 <label>alpha <output>{state.alpha.toFixed(2)}</output><input aria-label="透明度 alpha" type="range" min="0" max="1" step=".05" value={state.alpha} onChange={e=>change({alpha:+e.target.value})}/></label>
 <label>深度权重指数 <output>{state.power}</output><input aria-label="透明深度权重" type="range" min="0" max="8" step="1" value={state.power} onChange={e=>change({power:+e.target.value})}/></label>
 <label><input aria-label="透明面交叉" type="checkbox" checked={state.crossing} onChange={e=>change({crossing:e.target.checked})}/>平面交叉</label><label><input aria-label="反转透明提交顺序" type="checkbox" checked={state.reverse} onChange={e=>change({reverse:e.target.checked})}/>反转提交顺序</label>
 </>}</fieldset>
 {kind==='ibl'&&<p className="lighting-explanation">预滤波层 r = 0.20 / 0.36 / 0.52 / 0.68 / 0.84 / 1.00；另有一层漫反射。每层 64×32、256 样本，当前镜面层坐标 {((state.roughness-.2)/.16).toFixed(2)}。这是经纬图集的离散层插值，不是 Three.js PMREM。环境改变才重建图集（{report.atlasBuilds??0} 次）；BRDF 积分为方便检查在 WGSL 计算着色器执行，未缓存 LUT。</p>}
 {i&&<section className="lighting-inspection"><h4>实际 GPU / 单点核对</h4><p>同一栅格点 UV：{vec(i.uv)}；以下为显示映射前的线性值。</p><dl>{i.gpu.map((value,index)=><div key={index}><dt>{labels[index]}</dt><dd>{vec(value)}{i.cpu&&<><br/>CPU：{vec(i.cpu[index])}<br/>最大差：{Math.max(...value.map((v,k)=>Math.abs(v-i.cpu![index][k]))).toExponential(3)}</>}</dd></div>)}</dl>
 {i.layers&&<><p>CPU 射线 / 平面参考：{i.layers.map(l=>'面 '+l.id+'，深度 '+l.depth.toFixed(5)).join('；')||'背景'}。</p><p>GPU 累积 RGBA：{vec(i.accum!)}；剩余透过率：{i.reveal?.toFixed(6)}。</p></>}
 {kind==='ibl'&&<><button disabled={!i.normal||report.referenceRunning} onClick={()=>engine.current?.generateReference()}>生成独立 CPU 半球参考</button>{report.referenceRunning&&<button onClick={()=>engine.current?.cancelReference()}>取消参考</button>}<p>{i.normal?'CPU 使用不同的均匀立体角序列与独立 BRDF 公式；32,768 → 65,536 样本仅提供收敛线索。':'此点位于球外，请重新选球面。'}</p>{i.reference&&<p>CPU 65,536：{vec(i.reference.high)}<br/>两档变化：{i.reference.convergence.toExponential(3)}<br/>GPU 有限积分 / CPU 差：{i.reference.error.toExponential(3)}</p>}</>}
 </section>}
 <p className="lighting-cost">每格 160×160；CPU 最近提交 {report.cpuMs?.toFixed(2)??'—'} ms；{kind==='ibl'?'GPU 积分阶段 '+(report.gpuMs==null?'不可用':report.gpuMs.toFixed(2)+' ms')+'（不含图集构建）。':'GPU 加权与透过率两遍 '+(report.gpuMs==null?'不可用':report.gpuMs.toFixed(2)+' ms')+'（不含排序对照与合成）。'}{kind==='transparency'?'WBOIT 使用 3 次累积 + 3 次透过率绘制，再合成；对象顺序绘制与参考是额外比较成本。':'预滤波构建与逐像素积分均参与本演示，不用于代表生产 IBL 的运行成本。'} 调试读回不计入提交读数。{report.device}</p>
 {link&&<label className="lighting-share">分享链接<input aria-label="新实验分享链接" readOnly value={link}/></label>}
 <footer><a href={embedded?'/labs/'+kind+'/'+lightingHash(state):'/articles/'+(kind==='ibl'?'ibl':'transparency')+'/#lab'}>{embedded?'携参数打开完整实验室':'返回文章实验章节'} →</a></footer>
 </section>;
}
