import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GpuSession,GpuTimer} from '../gpu/device';
import {RevisionGate} from '../gpu/contracts';
import meshSource from '../../shaders/gpu/shadow-mesh.wgsl?raw';
import resolveSource from '../../shaders/gpu/shadow-resolve.wgsl?raw';
import displaySource from '../../shaders/gpu/present.wgsl?raw';
import {createShadowScene,type ShadowScene} from './scene';
import {shadowGeometryKey,shadowReferenceKey} from './state';
import {areaLightVisibilitySample,cpuShadowTexelDepth,evaluatePcf,pointVisibility} from './math';
import type {ShadowInspection,ShadowReference,ShadowReport,ShadowSample,ShadowState} from './types';
import type {Vec3} from '../ray/types';
const WIDTH=320,HEIGHT=200,DEBUG_WIDTH=332;
const algorithmIndex=(s:ShadowState)=>['hard','pcf','pcss'].indexOf(s.algorithm);
const cameraKey=(s:ShadowState)=>JSON.stringify(s.camera);
export class ShadowWebGPURenderer {
 canvas=document.createElement('canvas');session!:GpuSession;timer!:GpuTimer;camera=new T.PerspectiveCamera(45,1.6,.1,50);lightCamera=new T.PerspectiveCamera(75,1,.5,25);controls:OrbitControls;observer:IntersectionObserver;geometry:ShadowScene;state:ShadowState;
 vertices!:GPUBuffer;colors!:GPUBuffer;count=0;cameraUniform!:GPUBuffer;lightUniform!:GPUBuffer;resolveUniform!:GPUBuffer;displayUniform!:GPUBuffer;debugBuffer!:GPUBuffer;
 shadow!:GPUTexture;cameraDepth!:GPUTexture;positions!:GPUTexture;normals!:GPUTexture;image!:GPUTexture;
 depthPipeline!:GPURenderPipeline;gbufferPipeline!:GPURenderPipeline;resolvePipeline!:GPURenderPipeline;inspectPipeline!:GPUComputePipeline;displayPipeline!:GPURenderPipeline;
 lightGroup!:GPUBindGroup;cameraGroup!:GPUBindGroup;resolveGroup!:GPUBindGroup;displayGroup!:GPUBindGroup;resolveLayout!:GPUBindGroupLayout;
 inspection:ShadowInspection|null=null;reference:ShadowReference|null=null;referenceProgress=0;selected:[number,number]|null=null;selectedAlgorithm:ShadowState['algorithm']|null=null;
 paused=false;visible=true;disposed=false;contextLost=false;pending=true;lightDirty=true;gbufferDirty=true;resolveDirty=true;inspectionDirty=false;frameRequest=0;scheduleGeneration=0;referenceRequest=0;referenceGeneration=0;applyingCamera=false;gate=new RevisionGate();pointerStart=[0,0];
 private constructor(public host:HTMLElement,s:ShadowState,public onReport:(r:ShadowReport)=>void){this.state=structuredClone(s);this.geometry=createShadowScene(s);host.style.aspectRatio='1.6';host.append(this.canvas);this.canvas.setAttribute('aria-label','WebGPU 真实光栅阴影；点击接收表面检查');this.controls=new OrbitControls(this.camera,this.canvas);this.controls.enableDamping=false;this.controls.minDistance=1;this.controls.maxDistance=35;this.lightCamera.position.set(-3.5,7,4.5);this.lightCamera.lookAt(0,0,0);this.lightCamera.updateMatrixWorld();this.applyCamera();this.controls.addEventListener('change',this.cameraChanged);this.canvas.addEventListener('pointerdown',this.pointerDown);this.canvas.addEventListener('pointerup',this.pointerUp);this.observer=new IntersectionObserver(([e])=>{this.visible=e.isIntersecting;if(this.visible)this.request();else this.cancelScheduled();});this.observer.observe(host);}
 static async create(host:HTMLElement,s:ShadowState,report:(r:ShadowReport)=>void){const e=new ShadowWebGPURenderer(host,s,report);try{await e.initialize();return e;}catch(error){e.dispose();throw error;}}
 private async initialize(){this.session=await GpuSession.create(this.canvas,error=>{this.contextLost=true;this.paused=true;this.cancelScheduled();this.clearSelection();this.onReport({ready:false,pending:false,error});});const d=this.session.device;this.timer=new GpuTimer(this.session);this.cameraUniform=this.session.buffer('shadow camera',64,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.lightUniform=this.session.buffer('shadow light',64,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.resolveUniform=this.session.buffer('shadow parameters',320,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.displayUniform=this.session.buffer('shadow display',16,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.debugBuffer=this.session.buffer('shadow 332 vec4 records',DEBUG_WIDTH*16,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC);
 const sampled=GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING;this.positions=this.session.texture('shadow world positions',WIDTH,HEIGHT,'rgba32float',sampled);this.normals=this.session.texture('shadow geometric normals',WIDTH,HEIGHT,'rgba32float',sampled);this.cameraDepth=this.session.texture('shadow camera depth',WIDTH,HEIGHT,'depth32float',GPUTextureUsage.RENDER_ATTACHMENT);this.createShadowTarget();this.uploadGeometry();
 const [mesh,resolve,display]=await Promise.all([this.session.shader(meshSource,'shadow raster'),this.session.shader('diagnostic(off, derivative_uniformity);\n'+resolveSource,'shadow resolve'),this.session.shader(displaySource,'shadow display')]);const vertex:GPUVertexState={module:mesh,entryPoint:'vertex',buffers:[{arrayStride:16,attributes:[{shaderLocation:0,offset:0,format:'float32x4'}]}]};const meshLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX,buffer:{type:'uniform'}}]});const pl=d.createPipelineLayout({bindGroupLayouts:[meshLayout]});this.depthPipeline=await d.createRenderPipelineAsync({layout:pl,vertex,primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less'}});this.gbufferPipeline=await d.createRenderPipelineAsync({layout:pl,vertex,fragment:{module:mesh,entryPoint:'fragment',targets:[{format:'rgba32float'},{format:'rgba32float'}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less'}});this.lightGroup=d.createBindGroup({layout:meshLayout,entries:[{binding:0,resource:{buffer:this.lightUniform}}]});this.cameraGroup=d.createBindGroup({layout:meshLayout,entries:[{binding:0,resource:{buffer:this.cameraUniform}}]});
 const stages=GPUShaderStage.FRAGMENT|GPUShaderStage.COMPUTE;this.resolveLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:stages,buffer:{type:'uniform'}},{binding:1,visibility:stages,texture:{sampleType:'unfilterable-float'}},{binding:2,visibility:stages,texture:{sampleType:'unfilterable-float'}},{binding:3,visibility:stages,texture:{sampleType:'depth'}},{binding:4,visibility:stages,buffer:{type:'read-only-storage'}},{binding:5,visibility:stages,buffer:{type:'storage'}}]});const rpl=d.createPipelineLayout({bindGroupLayouts:[this.resolveLayout]});this.resolvePipeline=await d.createRenderPipelineAsync({layout:rpl,vertex:{module:resolve,entryPoint:'vertex'},fragment:{module:resolve,entryPoint:'fragment',targets:[{format:'rgba32float'}]},primitive:{topology:'triangle-list'}});this.inspectPipeline=await d.createComputePipelineAsync({layout:rpl,compute:{module:resolve,entryPoint:'inspect'}});const dl=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'unfilterable-float'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}}]});this.displayPipeline=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[dl]}),vertex:{module:display,entryPoint:'vertex'},fragment:{module:display,entryPoint:'fragment',targets:[{format:this.session.format}]},primitive:{topology:'triangle-list'}});this.rebind();this.resizeCanvas();this.configureLight();this.onReport({state:this.exportState(),pending:true,triangles:this.geometry.triangleCount,device:`WebGPU · ${this.session.adapter.vendor} / ${this.session.adapter.architecture}`});this.request();}
 private uploadGeometry(){if(this.vertices)this.session.release(this.vertices);if(this.colors)this.session.release(this.colors);const data:number[]=[],colors:number[]=[];for(const mesh of this.geometry.meshes){mesh.updateMatrixWorld(true);const geo=mesh.geometry,p=geo.getAttribute('position'),indices=geo.index,id=Number(mesh.userData.objectId),v=new T.Vector3();for(let j=0;j<(indices?.count??p.count);j++){v.fromBufferAttribute(p,indices?indices.getX(j):j).applyMatrix4(mesh.matrixWorld);data.push(v.x,v.y,v.z,id);}colors.push(...(mesh.material as T.MeshBasicMaterial).color.toArray(),1);}this.count=data.length/4;this.vertices=this.session.buffer('shadow scene vertices',data.length*4,GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST);this.colors=this.session.buffer('shadow material colors',colors.length*4,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST);this.session.device.queue.writeBuffer(this.vertices,0,new Float32Array(data));this.session.device.queue.writeBuffer(this.colors,0,new Float32Array(colors));}
 private createShadowTarget(){if(this.shadow)this.session.release(this.shadow);this.shadow=this.session.texture('light depth',this.state.resolution,this.state.resolution,'depth32float',GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING);}
 private rebind(){this.resolveGroup=this.session.device.createBindGroup({layout:this.resolveLayout,entries:[{binding:0,resource:{buffer:this.resolveUniform}},{binding:1,resource:this.positions.createView()},{binding:2,resource:this.normals.createView()},{binding:3,resource:this.shadow.createView()},{binding:4,resource:{buffer:this.colors}},{binding:5,resource:{buffer:this.debugBuffer}}]});}
 private resizeCanvas(){this.canvas.width=WIDTH*(this.state.compare?2:1);this.canvas.height=HEIGHT*(this.state.compare?2:1);if(this.image)this.session.release(this.image);this.image=this.session.texture('resolved shadows',this.canvas.width,this.canvas.height,'rgba32float',GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING);this.displayGroup=this.session.device.createBindGroup({layout:this.displayPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:this.image.createView()},{binding:1,resource:{buffer:this.displayUniform}}]});this.session.device.queue.writeBuffer(this.displayUniform,0,new Float32Array([this.canvas.width,this.canvas.height,0,1]));}
 private configureLight(){this.lightCamera.fov=this.state.fov;this.lightCamera.updateProjectionMatrix();this.lightCamera.updateMatrixWorld();this.camera.updateMatrixWorld();let minimum=Infinity;const p=new T.Vector3();for(const primitive of this.geometry.primitives)for(const v of [primitive.a,primitive.b,primitive.c])minimum=Math.min(minimum,-p.set(...v).applyMatrix4(this.lightCamera.matrixWorldInverse).z);const data=new Float32Array(80);data.set(this.lightCamera.matrixWorldInverse.elements,0);data.set(this.lightCamera.projectionMatrix.elements,16);data.set(this.lightCamera.matrixWorld.elements,32);data.set(this.lightCamera.projectionMatrixInverse.elements,48);data.set([.5,25,Math.tan(this.state.fov*Math.PI/360),Math.max(.5,minimum)],64);data.set([this.state.bias,this.state.filterRadius,this.state.lightSize,+this.state.planeCorrection],68);data.set([algorithmIndex(this.state),['lit','visibility','map'].indexOf(this.state.view),+this.state.compare,0],72);data.set([...(this.selected??[.5,.5]),this.canvas.width,this.canvas.height],76);const d=this.session.device;d.queue.writeBuffer(this.resolveUniform,0,data);d.queue.writeBuffer(this.cameraUniform,0,new Float32Array(new T.Matrix4().multiplyMatrices(this.camera.projectionMatrix,this.camera.matrixWorldInverse).elements));d.queue.writeBuffer(this.lightUniform,0,new Float32Array(new T.Matrix4().multiplyMatrices(this.lightCamera.projectionMatrix,this.lightCamera.matrixWorldInverse).elements));}
 private applyCamera(){this.applyingCamera=true;this.camera.position.set(...this.state.camera.position);this.controls.target.set(...this.state.camera.target);this.camera.lookAt(this.controls.target);this.controls.update();this.camera.updateMatrixWorld();this.applyingCamera=false;}
 private cameraChanged=()=>{if(this.applyingCamera||this.disposed)return;this.state.camera={position:this.camera.position.toArray() as Vec3,target:this.controls.target.toArray() as Vec3};this.clearSelection();this.gbufferDirty=true;this.invalidate();this.onReport({state:this.exportState()});this.request();};
 private pointerDown=(e:PointerEvent)=>{this.pointerStart=[e.clientX,e.clientY];};private pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-this.pointerStart[0],e.clientY-this.pointerStart[1])>5)return;const b=this.canvas.getBoundingClientRect();let u=(e.clientX-b.left)/b.width,v=(e.clientY-b.top)/b.height;if(u<0||u>=1||v<0||v>=1)return;if(this.state.compare){const panel=Math.floor(v*2)*2+Math.floor(u*2);if(panel===3)return;const algorithm=(['hard','pcf','pcss'] as const)[panel];if(algorithm!==this.state.algorithm)this.update({...this.state,algorithm});u=u*2%1;v=v*2%1;}else if(this.state.view==='map')return;this.pick(u,1-v);};
 private cancelScheduled(){this.scheduleGeneration++;cancelAnimationFrame(this.frameRequest);this.frameRequest=0;}
 private request(){if(!this.resolvePipeline||this.disposed||this.contextLost||this.paused||!this.visible||this.frameRequest||!this.resolveDirty)return;this.frameRequest=requestAnimationFrame(()=>{this.frameRequest=0;this.render();});}
 private invalidate(){this.gate.advance();this.resolveDirty=true;this.pending=true;this.inspectionDirty=!!this.selected;this.inspection=null;this.onReport({pending:true,inspection:null,gpuMs:null});}
 private clearSelection(){this.gate.advance();this.selected=null;this.selectedAlgorithm=null;this.inspection=null;this.inspectionDirty=false;this.cancelReference();this.onReport({inspection:null});}
 exportState(){return structuredClone(this.state);}
 update(input:ShadowState){if(this.disposed)return;const next=structuredClone(input),previous=this.state,geometryChanged=shadowGeometryKey(previous)!==shadowGeometryKey(next),cameraChanged=cameraKey(previous)!==cameraKey(next),referenceChanged=shadowReferenceKey(previous)!==shadowReferenceKey(next);this.cancelScheduled();this.state=next;if(geometryChanged||cameraChanged)this.clearSelection();else if(referenceChanged)this.cancelReference();if(geometryChanged){this.geometry.dispose();this.geometry=createShadowScene(next);this.uploadGeometry();this.lightDirty=true;this.gbufferDirty=true;}if(cameraChanged){this.applyCamera();this.gbufferDirty=true;}if(previous.resolution!==next.resolution){this.createShadowTarget();this.lightDirty=true;}if(previous.fov!==next.fov)this.lightDirty=true;if(geometryChanged||previous.resolution!==next.resolution)this.rebind();if(previous.compare!==next.compare)this.resizeCanvas();this.invalidate();this.onReport({state:this.exportState(),triangles:this.geometry.triangleCount});this.request();}
 setPaused(value:boolean){this.cancelScheduled();this.paused=value;this.onReport({paused:value});if(!value)this.request();}step(){if(!this.disposed&&!this.contextLost&&this.resolvePipeline){this.cancelScheduled();this.render();}}
 private render(){this.configureLight();const start=performance.now(),cmd=this.session.device.createCommandEncoder();if(this.lightDirty){const p=cmd.beginRenderPass({colorAttachments:[],depthStencilAttachment:{view:this.shadow.createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1}});p.setPipeline(this.depthPipeline);p.setBindGroup(0,this.lightGroup);p.setVertexBuffer(0,this.vertices);p.draw(this.count);p.end();this.lightDirty=false;}if(this.gbufferDirty){const p=cmd.beginRenderPass({colorAttachments:[this.positions,this.normals].map(t=>({view:t.createView(),loadOp:'clear' as const,storeOp:'store' as const,clearValue:[0,0,0,0]})),depthStencilAttachment:{view:this.cameraDepth.createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1}});p.setPipeline(this.gbufferPipeline);p.setBindGroup(0,this.cameraGroup);p.setVertexBuffer(0,this.vertices);p.draw(this.count);p.end();this.gbufferDirty=false;}const p=cmd.beginRenderPass({timestampWrites:this.timer.writes(),colorAttachments:[{view:this.image.createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});p.setPipeline(this.resolvePipeline);p.setBindGroup(0,this.resolveGroup);p.draw(3);p.end();const timed=this.timer.resolve(cmd);const display=cmd.beginRenderPass({colorAttachments:[{view:this.session.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});display.setPipeline(this.displayPipeline);display.setBindGroup(0,this.displayGroup);display.draw(3);display.end();this.session.device.queue.submit([cmd.finish()]);this.resolveDirty=false;this.pending=false;const token=this.scheduleGeneration;this.onReport({ready:true,pending:false,cpuMs:performance.now()-start,state:this.exportState()});if(timed)this.timer.read().then(gpuMs=>{if(!this.disposed&&token===this.scheduleGeneration)this.onReport({gpuMs});}).catch(()=>{});if(this.selected&&this.inspectionDirty)void this.inspect();}
 pick(u=.5,v=.5){if(this.disposed||this.contextLost||!Number.isFinite(u)||!Number.isFinite(v))return;this.cancelScheduled();this.cancelReference();this.selected=[(Math.min(WIDTH-1,Math.max(0,Math.floor(u*WIDTH)))+.5)/WIDTH,(Math.min(HEIGHT-1,Math.max(0,Math.floor(v*HEIGHT)))+.5)/HEIGHT];this.selectedAlgorithm=this.state.algorithm;this.inspectionDirty=true;if(this.resolveDirty)this.render();else void this.inspect();}
 private async inspect(){if(!this.selected)return;const token=this.gate.advance();this.inspection=null;this.onReport({inspection:null});this.configureLight();const cmd=this.session.device.createCommandEncoder(),p=cmd.beginComputePass();p.setPipeline(this.inspectPipeline);p.setBindGroup(0,this.resolveGroup);p.dispatchWorkgroups(1);p.end();this.session.device.queue.submit([cmd.finish()]);try{const data=new Float32Array(await this.session.readBuffer(this.debugBuffer,DEBUG_WIDTH*16));if(this.disposed||!this.gate.accepts(token))return;
  this.inspectionDirty=false;
  if(data[22]<.5){this.selected=null;this.inspection=null;this.onReport({inspection:null});return;}
  const position:Vec3=[data[0],data[1],data[2]],normal:Vec3=[data[4],data[5],data[6]];
  const searches=Math.max(0,Math.min(81,Math.round(data[18]))),filters=Math.max(0,Math.min(81,Math.round(data[19])));
  const samples:ShadowSample[]=[];
  for(let index=0;index<searches+filters;index++){
   const offset=(8+index*2)*4;
   samples.push({uv:[data[offset],data[offset+1]],depth:data[offset+2],receiver:data[offset+3],visible:data[offset+4],valid:data[offset+5]>.5,blocker:data[offset+6]>.5,stage:data[offset+7]<.5?'search':'filter'});
  }
  const covered=data[7]>.5,filterSamples=samples.filter(sample=>sample.stage==='filter');
  const independentlyAveraged=filters?evaluatePcf(filterSamples).visibility:covered&&data[15]===0?1:null;
  const map=cpuShadowTexelDepth(this.geometry.primitives,[data[8],data[9]],this.state.resolution,this.lightCamera.matrixWorld,this.lightCamera.projectionMatrixInverse,.5,25);
  this.inspection={uv:this.selected,position,normal,objectId:Math.round(data[3]),lightUv:[data[8],data[9]],receiverDepth:data[10],storedDepth:data[11],receiverDistance:data[12],storedDistance:data[13],visibility:data[14],blockerCount:Math.round(data[15]),blockerDistance:data[16],radiusTexels:data[17],searchRadiusTexels:data[20],covered,samples,cpuMapDepth:map?.depth??null,mapDepthError:map&&data[11]>=0?Math.abs(map.depth-data[11]):null,cpuVisibility:pointVisibility(position,normal,this.lightCamera.position.toArray() as Vec3,this.geometry.primitives),mathError:covered&&independentlyAveraged!==null?Math.abs(independentlyAveraged-data[14]):null};
  this.onReport({inspection:this.inspection});
 }catch(error){if(!this.disposed&&this.gate.accepts(token))this.onReport({error:'阴影检查读回失败：'+String(error),inspection:null});}}
 generateReference() {
  if(this.disposed||this.contextLost||!this.inspection)return;
  this.cancelReference();
  const token=this.referenceGeneration,position=[...this.inspection.position] as Vec3,normal=[...this.inspection.normal] as Vec3,primitives=this.geometry.primitives;
  const center=this.lightCamera.position.toArray() as Vec3;
  const right=new T.Vector3().setFromMatrixColumn(this.lightCamera.matrixWorld,0).multiplyScalar(this.state.lightSize).toArray() as Vec3;
  const up=new T.Vector3().setFromMatrixColumn(this.lightCamera.matrixWorld,1).multiplyScalar(this.state.lightSize).toArray() as Vec3;
  const seed=this.state.seed;let count=0,total=0,checkpoint=0;
  const tick=()=>{
   if(this.disposed||token!==this.referenceGeneration)return;
   this.referenceRequest=0;
   for(let batch=0;batch<32&&count<1024;batch++){
    total+=areaLightVisibilitySample(position,normal,primitives,{center,u:right,v:up,index:count,capacity:1024,seed,nearEpsilon:1e-4});count++;
    if(count===512)checkpoint=total/512;
   }
   this.referenceProgress=count/1024;
   if(count<1024)this.referenceRequest=requestAnimationFrame(tick);
   else this.reference={value:total/count,checkpoint,convergence:Math.abs(total/count-checkpoint),samples:count};
   this.onReport({referenceProgress:this.referenceProgress,reference:this.reference});
  };
  this.referenceRequest=requestAnimationFrame(tick);
 }
 cancelReference() {
  this.referenceGeneration++;cancelAnimationFrame(this.referenceRequest);this.referenceRequest=0;
  this.reference=null;this.referenceProgress=0;
  if(!this.disposed)this.onReport({reference:null,referenceProgress:0});
 }
 dispose(){if(this.disposed)return;this.disposed=true;this.cancelScheduled();this.cancelReference();this.gate.advance();this.observer.disconnect();this.controls.dispose();this.canvas.removeEventListener('pointerdown',this.pointerDown);this.canvas.removeEventListener('pointerup',this.pointerUp);this.geometry.dispose();this.timer?.dispose();this.session?.dispose();this.canvas.remove();}
}
