import ObservationGuide from '../reading/ObservationGuide';
import {ssrGuides} from '../reading/guides';
import {useEffect,useRef,useState} from 'react';
import type {SSRRenderer} from '../../lib/ssr/renderer';
import type {SSRReport,SSRState} from '../../lib/ssr/types';
import {decodeSSRState,defaultSSRState,ssrHref} from '../../lib/ssr/state';
import Inspection from './Inspection';
import './ssr.css';
const tasks=[
 {name:'检查一条路径',question:'镜面光线被投到哪里，哪一次深度比较接受了命中？',operation:'点击地面镜，逐步查看投影路径与深度曲线；先用平涂模型和屏幕步进隔离几何问题。',patch:{preset:'gallery',method:'screen',steps:192,stride:1,thickness:.08,shading:'flat',compare:true}},
 {name:'步长与厚度',question:'细条旁的命中，来自准确跨越还是厚度容差？',operation:'在细条场景比较固定视空间步长与屏幕步进；一次只改变步长、步数或厚度，检查漏采样和对象 ID。',patch:{preset:'thin',method:'view',viewStep:.7,steps:128,thickness:.06,shading:'flat',compare:true}},
 {name:'缺失的一层',question:'被前层挡住的物体，增加步数能让深度图恢复它吗？',operation:'比较悬空遮挡板后的镜中目标，再横移目标或转动相机；用完整几何对照区分没有信息与真正未命中。',patch:{preset:'hidden',method:'screen',steps:256,stride:1,thickness:.04,shading:'flat',compare:true}},
] satisfies Array<{name:string;question:string;operation:string;patch:Partial<SSRState>}>;
export default function SSRLab({embedded=false}:{embedded?:boolean}){
 const host=useRef<HTMLDivElement>(null),engine=useRef<SSRRenderer|null>(null),stateRef=useRef(defaultSSRState()),reportRef=useRef<SSRReport>({}),example=useRef<SSRState|null>(null);
 const [state,setState]=useState(defaultSSRState),[report,setReport]=useState<SSRReport>({}),[attempt,setAttempt]=useState(0),[task,setTask]=useState(-1),[share,setShare]=useState(''),[notice,setNotice]=useState('点击地面镜；检查面板只在选点或参数变化后读回。');
 function receive(next:SSRReport){reportRef.current={...reportRef.current,...next};setReport(reportRef.current);if(next.state){stateRef.current=next.state;setState(next.state);}}
 useEffect(()=>{let disposed=false;reportRef.current={pending:true,ready:false};setReport(reportRef.current);const parsed=attempt?{state:stateRef.current}:embedded?{state:defaultSSRState()}:decodeSSRState(location.hash);stateRef.current=parsed.state;setState(parsed.state);if(parsed.notice)setNotice(parsed.notice);
  import('../../lib/ssr/renderer').then(({SSRRenderer})=>{if(disposed||!host.current)return;try{engine.current=new SSRRenderer(host.current,parsed.state,receive);}catch(error){receive({ready:false,pending:false,error:error instanceof Error?error.message:String(error)});}}).catch(error=>receive({ready:false,pending:false,error:String(error)}));
  const restore=()=>{if(embedded)return;const decoded=decodeSSRState(location.hash);engine.current?.update(decoded.state);setNotice(decoded.notice??'已恢复场景、相机与步进条件。');};window.addEventListener('hashchange',restore);
  return()=>{disposed=true;window.removeEventListener('hashchange',restore);engine.current?.dispose();engine.current=null;};
 },[attempt,embedded]);
 useEffect(()=>{if(embedded)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_ssr_experiment',description:'只读当前SSR参数、实际GPU逐步记录与完整几何CPU对照。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');return {...reportRef.current,state:engine.current?.exportState()??stateRef.current};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[embedded]);
 function change(patch:Partial<SSRState>){engine.current?.update({...stateRef.current,...patch});}
 function load(index:number){const next={...defaultSSRState(),...tasks[index].patch};example.current=structuredClone(next);setTask(index);engine.current?.setPaused(false);engine.current?.update(next);setNotice('已载入任务起点；恢复按钮会回到这组条件。');}
 async function sharing(){const current=stateRef.current,url=new URL(ssrHref({...current,learning:current.learning??{article:'ssr',chapter:'lab'}}),location.origin).href;setShare(url);try{await navigator.clipboard.writeText(url);setNotice('链接已复制；恢复时重建相同输入。');}catch{setNotice('请复制下方实验链接。');}}
 const ready=!!report.ready,pending=!!report.pending,brief=tasks[Math.max(task,0)];
 return <section className="ssr-lab"><header className="ssr-heading"><span className="eyebrow">SCREEN-SPACE REFLECTIONS / 真实光栅输入</span><h3>沿着反射方向，走到屏幕信息的边界。</h3><p>实际网格 → 原生相机深度、法线与线性颜色 → SSR。完整几何对照使用相同网格与同一颜色模型。</p></header>
 <div className="ssr-task"><div className="small-tabs">{tasks.map((t,i)=><button key={t.name} disabled={!ready||pending} aria-pressed={task===i} onClick={()=>load(i)}>{i+1} · {t.name}</button>)}</div><h4>{brief.question}</h4><p>{brief.operation}</p>{task<0&&<p className="fine">点击任务载入起点；默认画面也可自由检查。</p>}</div>
 <ObservationGuide key={task} {...ssrGuides[Math.max(0,task)]}/>
 <div className="ssr-toolbar"><button disabled={!ready} aria-pressed={state.compare} onClick={()=>change({compare:!state.compare})}>四格对照</button><span role="status">{report.error?'静态说明可读':!ready?'初始化中…':pending?'等待当前条件计算':'WebGL2 · 就绪'}</span></div>
 <div className="ssr-viewport" ref={host}>{state.compare&&<div className="ssr-labels">{['SSR · '+(state.method==='screen'?'屏幕步进':'视空间步进'),'完整几何 · 同模型','平均绝对差 ×4','SSR 终止分类'].map(label=><span key={label}>{label}</span>)}</div>}
 {!ready&&<div className="ssr-fallback"><strong>{report.error??'准备真实 G-buffer 与完整几何对照…'}</strong><svg viewBox="0 0 320 115" role="img" aria-label="静态示意：镜面反射投影到只存一层表面的深度图"><path d="M20 94h280 M35 20l95 74 90-65" fill="none" stroke="#52849a" strokeWidth="3"/><rect x="210" y="12" width="55" height="33" fill="#ce996c"/><text x="20" y="110">镜面</text><text x="115" y="18">静态示意 · 不是 GPU 读数</text></svg><p>反射方向投影到相机深度图；缺少屏幕外与前层后面的几何。完整几何查询可以验证这类信息缺失。</p>{report.error&&<button onClick={()=>setAttempt(n=>n+1)}>重试 SSR 实验</button>}</div>}
 {pending&&ready&&<div className="ssr-pending">输入已变化；旧检查隐藏，单步或恢复后重新计算。</div>}
 {report.inspection&&!pending&&<span className="ssr-pick" style={{left:`${report.inspection.uv[0]*(state.compare?50:100)}%`,top:`${(1-report.inspection.uv[1])*(state.compare?50:100)}%`}}/>}</div>
 <div className="ssr-actions"><button disabled={!ready||pending} onClick={()=>engine.current?.pick(.52,.3)}>检查地面镜示例</button><button disabled={!ready} onClick={()=>engine.current?.setPaused(!report.paused)}>{report.paused?'恢复更新':'暂停更新'}</button><button disabled={!ready} onClick={()=>engine.current?.step()}>单步计算</button><button disabled={!ready} onClick={()=>{engine.current?.setPaused(false);engine.current?.update(structuredClone(example.current??defaultSSRState()));}}>恢复任务示例</button><button onClick={sharing}>分享 SSR 实验</button></div><p className="fine ssr-notice">{notice}</p>
 <fieldset disabled={!ready}><div className="ssr-controls"><label>步进方式<select aria-label="SSR 步进方式" value={state.method} onChange={e=>change({method:e.target.value as SSRState['method']})}><option value="screen">透视校正屏幕 DDA · 教学简化</option><option value="view">固定视空间步长 · 基线</option></select></label>
 <label>步数预算<select aria-label="SSR 步数预算" value={state.steps} onChange={e=>change({steps:+e.target.value})}>{![16,32,64,128,192,256].includes(state.steps)&&<option value={state.steps}>{state.steps}（恢复值）</option>}{[16,32,64,128,192,256].map(n=><option key={n} value={n}>{n} 步</option>)}</select></label>
 {state.method==='screen'?<label>屏幕间隔 <output>{state.stride} px</output><input aria-label="SSR 屏幕间隔" type="range" min="1" max="8" step="1" value={state.stride} onChange={e=>change({stride:+e.target.value})}/></label>:<label>视空间步长 <output>{state.viewStep.toFixed(3)}</output><input aria-label="SSR 视空间步长" type="range" min=".025" max="1" step=".025" value={state.viewStep} onChange={e=>change({viewStep:+e.target.value})}/></label>}
 <label>轴向厚度容差 <output>{state.thickness.toFixed(3)}</output><input aria-label="SSR 厚度容差" type="range" min=".001" max="1" step=".001" value={state.thickness} onChange={e=>change({thickness:+e.target.value})}/></label>
 <label>最大射线距离 <output>{state.range.toFixed(1)}</output><input aria-label="SSR 距离范围" type="range" min="2" max="30" step=".5" value={state.range} onChange={e=>change({range:+e.target.value})}/></label>
 <label>目标横移 <output>{state.offset.toFixed(1)}</output><input aria-label="SSR 目标横移" type="range" min="-7" max="7" step=".1" value={state.offset} onChange={e=>change({offset:+e.target.value})}/></label></div>
 <details className="ssr-options" open={embedded?undefined:true}><summary>场景、颜色模型与显示</summary><div className="ssr-controls"><label>场景<select aria-label="SSR 场景" value={state.preset} onChange={e=>change({preset:e.target.value as SSRState['preset']})}><option value="gallery">几何展台</option><option value="thin">细条与深度断层</option><option value="hidden">悬空遮挡与后层</option></select></label><label>共同颜色模型<select aria-label="SSR 颜色模型" value={state.shading} onChange={e=>change({shading:e.target.value as SSRState['shading']})}><option value="flat">平涂线性颜色 · 几何诊断</option><option value="local">固定方向局部明暗</option></select></label><label>单幅显示<select aria-label="SSR 显示信号" disabled={state.compare} value={state.view} onChange={e=>change({view:e.target.value as SSRState['view']})}><option value="reflection">SSR 反射</option><option value="status">SSR 终止分类</option><option value="depth">真实相机轴向深度</option></select></label></div><p className="fine">地面镜 y=0；起点沿几何法线偏移 {state.epsilon.toFixed(4)} 世界单位。厚度是光相机无关的主相机轴距公差，不是物体厚度。默认平涂模型不计算阴影或全局光照。</p></details></fieldset>
 <p className="ssr-legend fine">绿色：深度命中 · 橙色：出屏 · 紫色：近面 · 蓝色：无深度 · 灰色：距离耗尽 · 黄色：步数耗尽 · 品红：无效。SSR 未命中使用同一常量环境。</p>
 {report.inspection&&!pending&&<Inspection data={report.inspection}/>}
 <div className="ssr-stats"><span>图像 <b>320 × 200 / 格</b></span><span>实际三角形 <b>{report.triangles??'—'}</b></span><span>CPU 提交 <b>{report.cpuMs===undefined?'—':report.cpuMs.toFixed(2)+' ms'}</b></span><span>GPU 当前展示合计 <b>{report.gpuMs==null?'不可用':report.gpuMs.toFixed(2)+' ms'}</b></span></div><p className="fine ssr-notice">四格计时包含 SSR 和完整几何对照，不代表单独 SSR 耗时；选点调试与 CPU 验证不在该计时范围。{report.device&&'设备：'+report.device}</p>
 {share&&<label className="ssr-share">实验链接<input aria-label="SSR 实验分享链接" readOnly value={share} onFocus={e=>e.target.select()}/></label>}
 <footer className="ssr-footer"><span>真实光栅输入 · 单层深度 · 确定性单次反射</span><a href={embedded?ssrHref({...state,learning:{article:'ssr',chapter:'lab'}}):'/articles/ssr/#'+(state.learning?.chapter??'lab')}>{embedded?'携当前条件打开完整实验':'返回文章章节'}</a></footer>
 </section>;
}
