import {useState} from 'react';
export default function HemisphereExplorer(){
 const [tilt,setTilt]=useState(15),[cone,setCone]=useState(40),[selected,setSelected]=useState(40);
 const a=tilt*Math.PI/180,n=[Math.sin(a),Math.cos(a),0],t=[Math.cos(a),-Math.sin(a),0],count=512;
 const dirs=Array.from({length:count},(_,i)=>{const u=(i+.5)/count,phi=i*2.39996322973,s=Math.sqrt(1-u*u);const d=n.map((x,j)=>x*u+t[j]*s*Math.cos(phi)+(j===2?s*Math.sin(phi):0));return {d,cos:u,visible:d[0]<Math.cos(cone*Math.PI/180)};});
 const A=dirs.reduce((sum,d)=>sum+(d.visible?2*d.cos/count:0),0),chosen=dirs[selected];
 const project=(d:number[],scale=1)=>[180+(d[0]+d[2]*.4)*130*scale,165-d[1]*120*scale+d[2]*45*scale];
 return <div className="slice-experiment"><div className="diagram-wrap"><span className="eyebrow">原理示意 / 半球方向与余弦权重</span><svg viewBox="0 0 400 270" role="img" aria-label="三维半球方向的投影，绿色可见、紫色被右侧圆锥遮挡"><ellipse cx="180" cy="165" rx="138" ry="48" fill="none" stroke="#d3dde4" strokeDasharray="4 5"/>{dirs.filter((_,i)=>i%4===0).map((d,i)=>{const p=project(d.d);return <circle key={i} cx={p[0]} cy={p[1]} r="2.4" fill={d.visible?'#378781':'#b6537c'}/>})}<line x1="180" y1="165" x2={project(n,1.15)[0]} y2={project(n,1.15)[1]} stroke="#2a6bbb" strokeWidth="3"/><line x1="180" y1="165" x2={project(chosen.d)[0]} y2={project(chosen.d)[1]} stroke="#c87927" strokeWidth="2"/><circle cx="180" cy="165" r="4" fill="#152d3a"/><text x={project(n,1.26)[0]} y={project(n,1.26)[1]}>n</text><text x="320" y="155">遮挡方向 +X</text><text x="110" y="250">绿：可见　紫：被遮挡</text></svg><p>遮挡圆锥固定在 +X，采样点集随法线旋转。观察总可见度变化；选中样本相对法线固定，所以它的余弦值保持不变。固定可见角域的权重比较见第 6 节。</p></div><div className="diagram-controls"><label>法线倾角 <output>{tilt}°</output><input aria-label="半球法线倾角" type="range" min="-70" max="70" value={tilt} onChange={e=>setTilt(+e.target.value)}/></label><label>遮挡圆锥半角 <output>{cone}°</output><input aria-label="遮挡圆锥半角" type="range" min="0" max="80" value={cone} onChange={e=>setCone(+e.target.value)}/></label><label>观察一个方向 <output>{selected+1}</output><input aria-label="半球方向" type="range" min="0" max="511" value={selected} onChange={e=>setSelected(+e.target.value)}/></label><div className="numbers"><div><small>半球可见度估计 A</small><strong>{A.toFixed(4)}</strong></div></div><p className="fine">选中方向 cos θ = {chosen.cos.toFixed(3)}，V = {chosen.visible?'1（可见）':'0（遮挡）'}。512 个均匀半球样本，贡献为 2V cos θ / 512；圆锥半角为 0 时 A = 1。</p><button onClick={()=>{setTilt(15);setCone(40);setSelected(40)}}>恢复本节示例</button></div></div>
}
