import {PerspectiveCamera} from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GpuSession,GpuTimer} from '../gpu/device';
import {RevisionGate,encodePasses} from '../gpu/contracts';
import source from '../../shaders/gpu/pbr.wgsl?raw';
import presentSource from '../../shaders/gpu/present.wgsl?raw';
import {colorToLinear,evaluateBrdf,integralSample} from './brdf';
import {pbrIntegrandKey} from './state';
import type {PbrState,PbrReport,PbrInspection,PbrIntegral,BrdfTerms,Vec3} from './types';
const views=['beauty','diffuse','specular','d','f','g'];
export class PbrWebGPURenderer {
 canvas=document.createElement('canvas');camera=new PerspectiveCamera(42,1.6,.1,50);controls:OrbitControls;session!:GpuSession;timer!:GpuTimer;
 uniforms!:GPUBuffer;displayUniforms!:GPUBuffer;debug!:GPUBuffer;image!:GPUTexture;compute!:GPUComputePipeline;inspectPipeline!:GPUComputePipeline;display!:GPURenderPipeline;group!:GPUBindGroup;displayGroup!:GPUBindGroup;
 state:PbrState;inspection:PbrInspection|null=null;integral:PbrIntegral|null=null;selected:[number,number]|null=null;paused=false;pending=true;disposed=false;lost=false;visible=true;displayDirty=false;dirty=true;inspectDirty=false;applying=false;frameRequest=0;integralRequest=0;integralGeneration=0;inspectionGate=new RevisionGate();generation=0;private pointer=[0,0];observer:IntersectionObserver;
 private constructor(public host:HTMLElement,state:PbrState,public onReport:(report:PbrReport)=>void){this.state=structuredClone(state);this.canvas.width=400;this.canvas.height=250;this.canvas.style.width='100%';this.canvas.style.height='100%';this.canvas.setAttribute('aria-label','WebGPU 材质球；拖动相机或点击表面检查');host.style.aspectRatio='1.6';host.append(this.canvas);this.controls=new OrbitControls(this.camera,this.canvas);this.controls.enableDamping=false;this.controls.minDistance=1;this.controls.maxDistance=20;this.applyCamera();this.controls.addEventListener('change',this.cameraChanged);this.canvas.addEventListener('pointerdown',this.pointerDown);this.canvas.addEventListener('pointerup',this.pointerUp);this.observer=new IntersectionObserver(([e])=>{this.visible=e.isIntersecting;if(this.visible)this.request();else this.cancelFrame();});this.observer.observe(host);}
 static async create(host:HTMLElement,state:PbrState,report:(r:PbrReport)=>void){const engine=new PbrWebGPURenderer(host,state,report);try{await engine.initialize();return engine;}catch(e){engine.dispose();throw e;}}
 private async initialize(){this.session=await GpuSession.create(this.canvas,message=>{this.lost=true;this.setPaused(true);this.inspectionGate.advance();this.cancelIntegral();this.onReport({ready:false,pending:false,inspection:null,error:message});});this.timer=new GpuTimer(this.session);const d=this.session.device;
 this.uniforms=this.session.buffer('PBR camera/material',208,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.displayUniforms=this.session.buffer('PBR display',16,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);this.debug=this.session.buffer('PBR 12 vec4 inspection',192,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC);this.image=this.session.texture('PBR linear image',400,250,'rgba32float',GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_SRC);
 const shader=await this.session.shader(source,'PBR compatibility WGSL'),display=await this.session.shader(presentSource,'PBR display');
 const layout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.COMPUTE,buffer:{type:'uniform'}},{binding:1,visibility:GPUShaderStage.COMPUTE,storageTexture:{access:'write-only',format:'rgba32float'}},{binding:2,visibility:GPUShaderStage.COMPUTE,buffer:{type:'storage'}}]});const pipelineLayout=d.createPipelineLayout({bindGroupLayouts:[layout]});
 this.compute=await d.createComputePipelineAsync({layout:pipelineLayout,compute:{module:shader,entryPoint:'render'}});this.inspectPipeline=await d.createComputePipelineAsync({layout:pipelineLayout,compute:{module:shader,entryPoint:'inspect'}});this.group=d.createBindGroup({layout,entries:[{binding:0,resource:{buffer:this.uniforms}},{binding:1,resource:this.image.createView()},{binding:2,resource:{buffer:this.debug}}]});
 const dl=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'unfilterable-float'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}}]});this.display=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[dl]}),vertex:{module:display,entryPoint:'vertex'},fragment:{module:display,entryPoint:'fragment',targets:[{format:this.session.format}]},primitive:{topology:'triangle-list'}});this.displayGroup=d.createBindGroup({layout:dl,entries:[{binding:0,resource:this.image.createView()},{binding:1,resource:{buffer:this.displayUniforms}}]});this.writeUniforms();const a=this.session.adapter;this.onReport({device:`WebGPU · ${a.vendor} / ${a.architecture} · ${a.fallback?'软件适配器':'非软件回退'} · timestamp ${a.timestamp?'可用':'不可用'}`,state:this.exportState(),pending:true});this.request();
 }
 private writeUniforms(){if(!this.uniforms)return;const s=this.state,data=new Float32Array(52),az=s.lightAzimuth*Math.PI/180,el=s.lightElevation*Math.PI/180;this.camera.updateMatrixWorld();data.set(this.camera.projectionMatrixInverse.elements,0);data.set(this.camera.matrixWorld.elements,16);data.set([...colorToLinear(s.baseColor),0],32);data.set([Math.sin(az)*Math.cos(el),Math.sin(el),Math.cos(az)*Math.cos(el),0],36);data.set([s.roughness,s.metallic,s.intensity,0],40);data.set([+s.compare,+s.shadows,views.indexOf(s.view),0],44);data.set(this.selected??[.5,.5],48);this.session.device.queue.writeBuffer(this.uniforms,0,data);this.session.device.queue.writeBuffer(this.displayUniforms,0,new Float32Array([400,250,s.exposure,views.indexOf(s.view)>=3?1:0]));}
 private applyCamera(){this.applying=true;this.camera.position.set(...this.state.camera.position);this.controls.target.set(...this.state.camera.target);this.camera.lookAt(this.controls.target);this.controls.update();this.camera.updateMatrixWorld();this.applying=false;}
 private cameraChanged=()=>{if(this.applying||this.disposed)return;this.state.camera={position:this.camera.position.toArray() as Vec3,target:this.controls.target.toArray() as Vec3};this.selected=null;this.invalidate();this.writeUniforms();this.onReport({state:this.exportState()});this.request();};
 private pointerDown=(e:PointerEvent)=>{this.pointer=[e.clientX,e.clientY];};private pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-this.pointer[0],e.clientY-this.pointer[1])>5)return;const b=this.canvas.getBoundingClientRect();this.pick((e.clientX-b.left)/b.width,1-(e.clientY-b.top)/b.height);};
 private cancelFrame(){this.generation++;cancelAnimationFrame(this.frameRequest);this.frameRequest=0;}
 private request(){if(!this.compute||this.disposed||this.lost||(this.paused&&this.dirty)||!this.visible||(!this.dirty&&!this.displayDirty)||this.frameRequest)return;this.frameRequest=requestAnimationFrame(()=>{this.frameRequest=0;if(!this.disposed&&!this.lost){if(this.dirty)this.render();else this.present();}});}
 private invalidate(){this.dirty=true;this.pending=true;this.inspectDirty=!!this.selected;this.inspection=null;this.inspectionGate.advance();this.cancelIntegral();this.onReport({pending:true,inspection:null,gpuMs:null});}
 exportState(){return structuredClone(this.state);}
 update(s:PbrState){if(this.disposed)return;const previous=this.state,changed=pbrIntegrandKey(previous)!==pbrIntegrandKey(s);this.cancelFrame();this.state=structuredClone(s);if(JSON.stringify(previous.camera)!==JSON.stringify(s.camera)||previous.compare!==s.compare)this.selected=null;this.applyCamera();this.writeUniforms();if(changed)this.invalidate();else if(previous.view!==s.view){this.dirty=true;this.pending=true;this.onReport({pending:true});}this.onReport({state:this.exportState()});if(!changed&&!this.pending)this.present();else if(!changed&&this.paused&&previous.view!==s.view)this.render();else this.request();}
 setPaused(value:boolean){this.cancelFrame();this.paused=value;this.onReport({paused:value});if(!value)this.request();}
 step(){if(this.compute&&!this.disposed&&!this.lost){this.cancelFrame();this.render();}}
 private presentPass(encoder:GPUCommandEncoder){const pass=encoder.beginRenderPass({colorAttachments:[{view:this.session.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});pass.setPipeline(this.display);pass.setBindGroup(0,this.displayGroup);pass.draw(3);pass.end();}
 private present(){if(!this.display||this.disposed||this.lost)return;if(!this.visible){this.displayDirty=true;return;}this.displayDirty=false;const encoder=this.session.device.createCommandEncoder();this.presentPass(encoder);this.session.device.queue.submit([encoder.finish()]);}
 private render(){this.writeUniforms();const d=this.session.device,encoder=d.createCommandEncoder(),start=performance.now(),tag=this.generation;let timed=false;
 encodePasses(encoder,[{name:'PBR shading',reads:['state'],writes:['linear'],encode:cmd=>{const p=cmd.beginComputePass({timestampWrites:this.timer.writes()});p.setPipeline(this.compute);p.setBindGroup(0,this.group);p.dispatchWorkgroups(50,32);p.end();timed=this.timer.resolve(cmd);}},{name:'display',reads:['linear'],writes:['canvas'],encode:cmd=>this.presentPass(cmd)}],['state']);d.queue.submit([encoder.finish()]);this.dirty=false;this.displayDirty=false;this.pending=false;this.onReport({ready:true,pending:false,cpuMs:performance.now()-start});if(timed)this.timer.read().then(ms=>{if(!this.disposed&&tag===this.generation)this.onReport({gpuMs:ms});}).catch(()=>{});if(this.selected&&this.inspectDirty)void this.inspect();}
 pick(u=.5,v=.5){if(!this.compute||this.disposed||this.lost||!Number.isFinite(u)||!Number.isFinite(v))return;this.cancelIntegral();this.selected=[(Math.min(399,Math.max(0,Math.floor(u*400)))+.5)/400,(Math.min(249,Math.max(0,Math.floor(v*250)))+.5)/250];this.inspectDirty=true;if(this.dirty)this.render();else void this.inspect();}
 private async inspect(){if(!this.selected)return;this.inspection=null;this.onReport({inspection:null});const selected:[number,number]=[...this.selected],token=this.inspectionGate.advance();this.writeUniforms();const cmd=this.session.device.createCommandEncoder(),p=cmd.beginComputePass();p.setPipeline(this.inspectPipeline);p.setBindGroup(0,this.group);p.dispatchWorkgroups(1);p.end();this.session.device.queue.submit([cmd.finish()]);try{const data=new Float32Array(await this.session.readBuffer(this.debug,192));if(this.disposed||!this.inspectionGate.accepts(token))return;this.inspectDirty=false;if(data[3]<0){this.selected=null;this.inspection=null;this.onReport({inspection:null});return;}const vec=(offset:number)=>Array.from(data.slice(offset,offset+3)) as Vec3;const material={baseColor:vec(44),roughness:data[7],metallic:data[19]},cpu=evaluateBrdf(material,vec(4),vec(32),vec(36));
 const terms:BrdfTerms={noL:data[8],noV:data[9],noH:data[10],voH:data[11],alpha:data[35],d:data[12],g1L:data[13],g1V:data[14],g:data[15],f0:vec(40),f:vec(16),diffuse:vec(20),specular:vec(24),brdf:vec(20).map((v,i)=>v+data[24+i]) as Vec3};const cpuRadiance=cpu.brdf.map(v=>v*data[27]*cpu.noL*data[23]) as Vec3,expected=[cpu.d,cpu.g1L,cpu.g1V,cpu.g,...cpu.f,...cpu.diffuse,...cpu.specular,...cpuRadiance],actual=[terms.d,terms.g1L,terms.g1V,terms.g,...terms.f,...terms.diffuse,...terms.specular,...vec(28)],error=Math.max(...expected.map((v,i)=>Math.abs(v-actual[i])/Math.max(1,Math.abs(v))));this.inspection={uv:selected,position:vec(0),normal:vec(4),objectId:data[3],material,viewDirection:vec(32),lightDirection:vec(36),visibility:data[23],intensity:data[27],terms,radiance:vec(28),cpu,cpuRadiance,maxRelativeError:error,valid:data[31]>.5&&Array.from(data).every(Number.isFinite)};this.onReport({inspection:this.inspection});}catch(e){if(!this.disposed&&this.inspectionGate.accepts(token))this.onReport({error:'检查读回失败：'+String(e),inspection:null});}}
 generateIntegral(){
  if(this.disposed||!this.inspection||this.inspection.terms.noV<=0)return;this.cancelIntegral();
  const token=this.integralGeneration,material=structuredClone(this.inspection.material),noV=this.inspection.terms.noV,samples=8192,d:Vec3=[0,0,0],s:Vec3=[0,0,0];let count=0,checkpoint:Vec3=[0,0,0];
  const tick=()=>{if(this.disposed||token!==this.integralGeneration)return;this.integralRequest=0;
   for(let batch=0;batch<256&&count<samples;batch++){const sample=integralSample(material,noV,count,samples);for(let c=0;c<3;c++){d[c]+=sample.diffuse[c];s[c]+=sample.specular[c];}count++;if(count===samples/2)checkpoint=d.map((v,c)=>(v+s[c])/count) as Vec3;}
   if(count<samples)this.integralRequest=requestAnimationFrame(tick);
   else{const diffuse=d.map(v=>v/samples) as Vec3,specular=s.map(v=>v/samples) as Vec3,total=diffuse.map((v,c)=>v+specular[c]) as Vec3;this.integral={diffuse,specular,total,samples,convergence:total.map((v,c)=>Math.abs(v-checkpoint[c])) as Vec3};}
   this.onReport({integral:this.integral,integralProgress:count/samples});
  };this.integralRequest=requestAnimationFrame(tick);
 }
 cancelIntegral(){this.integralGeneration++;cancelAnimationFrame(this.integralRequest);this.integralRequest=0;this.integral=null;if(!this.disposed)this.onReport({integral:null,integralProgress:0});}
 dispose(){if(this.disposed)return;this.disposed=true;this.cancelFrame();this.inspectionGate.advance();this.cancelIntegral();this.observer.disconnect();this.controls.dispose();this.canvas.removeEventListener('pointerdown',this.pointerDown);this.canvas.removeEventListener('pointerup',this.pointerUp);this.timer?.dispose();this.session?.dispose();this.canvas.remove();}
}
