import {useState} from 'react';
import type {SceneSnapshot} from '../../lib/ray/types';
import type {PathInspection} from '../../lib/ray/progressive';
const reasons=['继续','未命中 / 环境','发光终点','散射上限','RR 终止','非法结果','预算溢出','零贡献','模式完成'];
export default function PathPanel({data,samples,snapshot,onSample}:{data:PathInspection;samples:number;snapshot:SceneSnapshot|null;onSample:(n:number)=>void}){
 const [step,setStep]=useState(0),[yaw,setYaw]=useState(-30);const selected=Math.min(step,Math.max(0,data.events.length-1)),e=data.events[selected];
 const center=[0,1.8,0];const a=yaw*Math.PI/180;const project=(p:number[])=>[215+((p[0]-center[0])*Math.cos(a)+(p[2]-center[2])*Math.sin(a))*28,205-((p[1]-center[1])*.8-(-(p[0]-center[0])*Math.sin(a)+(p[2]-center[2])*Math.cos(a))*.35)*28];
 return <section className="ray-inspection path-inspection"><header><span className="eyebrow">实际 GPU 路径 / 样本 {data.sample} / 帧 {data.frame}</span><h4>{data.mode===3?'间接分量 B 的路径':'逐跳检查贡献'} <span className={data.status===0?'good':'bad'}>{data.status===0?'有效计算':'无效 / 溢出'}</span></h4></header><div className="ray-inspection-grid"><div><svg viewBox="0 0 430 350" role="img" aria-label="当前GPU样本实际经过的路径顶点"><g fill="none" stroke="#c4d3dd" strokeWidth=".8">{snapshot?.primitives.map(p=>p.kind==='triangle'?<polygon key={p.id} points={[p.a,p.b,p.c].map(v=>project(v).join(',')).join(' ')}/>:<g key={p.id}>{[0,1,2].map(axis=><polyline key={axis} points={Array.from({length:33},(_,i)=>{const v=[...p.a],a=i*Math.PI/16;v[(axis+1)%3]+=p.radius*Math.cos(a);v[(axis+2)%3]+=p.radius*Math.sin(a);return project(v).join(',')}).join(' ')}/>)}</g>)}</g>{data.events.map((p,i)=>{const end=p.primitiveId>=0?p.position:p.origin.map((v,j)=>v+p.direction[j]*2),s=project(p.origin),t=project(end);return <g key={i}><line x1={s[0]} y1={s[1]} x2={t[0]} y2={t[1]} stroke={i===selected?'#da9230':'#8da7b7'} strokeWidth={i===selected?3:1.2} strokeDasharray={p.primitiveId<0?'4 3':''}/><circle cx={t[0]} cy={t[1]} r="4" fill={i===selected?'#c87625':'#3674a1'}/><text x={t[0]+6} y={t[1]-5}>{i+1}</text></g>})}<text x="15" y="331">只展示本次样本；不是累积画面的所有路径。</text></svg><label>观察方位<input aria-label="路径观察方向" type="range" min="-180" max="180" value={yaw} onChange={event=>setYaw(+event.target.value)}/></label><label>路径事件 <output>{selected+1} / {data.events.length}</output><input aria-label="路径事件" type="range" min="0" max={Math.max(0,data.events.length-1)} value={selected} onChange={event=>setStep(+event.target.value)}/></label><label>冻结样本编号<input aria-label="检查样本编号" type="number" min="0" max={Math.max(samples-1,0)} value={data.sample} onChange={event=>onSample(Math.max(0,Math.min(samples-1,+event.target.value)))}/></label></div><div><dl>{[
 ['本样本线性贡献',data.radiance.map(x=>x.toFixed(5)).join(', ')],['终止原因',reasons[data.termination]??data.termination],['已处理散射',data.scattering],['相机 / 延续 / 阴影查询',data.rayCounts.slice(0,3).join(' / ')],['节点 / 图元测试',`${data.nodes} / ${data.tests}`],['日志',data.truncated?'仅前8事件，计算未截断':'完整'],
 ...(e?[['射线起点',e.origin.map(x=>x.toFixed(4)).join(', ')],['射线方向',e.direction.map(x=>x.toFixed(4)).join(', ')],['命中位置',e.primitiveId>=0?e.position.map(x=>x.toFixed(4)).join(', '):'—'],['几何法线',e.primitiveId>=0?e.normal.map(x=>x.toFixed(4)).join(', '):'—'],['命中距离',e.primitiveId>=0?e.distance.toFixed(5):'—'],['命中图元 / 对象 / 材质',`${e.primitiveId} / ${e.objectId} / ${e.materialId}`],['到达时吞吐量 β',e.beta.map(x=>x.toFixed(5)).join(', ')],['生成该射线的 PDF',e.generatedPdf.toExponential(3)],['光源 / BSDF PDF',`${e.lightPdf.toExponential(3)} / ${e.bsdfPdf.toExponential(3)}`],['MIS 权重',e.misWeight.toFixed(5)],['本事件终止',reasons[e.termination]??e.termination]]:[])
 ].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="fine">所有值来自同一积分内核的调试分支。理想镜面的连续 PDF 为 0，离散事件另行处理；正常零贡献仍计入样本平均。</p>{data.mode===3&&<p className="ray-verdict">本表只记录 B 的路径。合成还使用独立的 16 个面积灯样本计算直接光；没有除以接收面反照率。</p>}</div></div></section>
}
