import {useEffect,useRef,useState} from 'react';
import {defaultRayState,decodeRayState,rayCamera,rayLessons,type RayState,type RayLesson} from '../../lib/ray/state';
import type {RayRenderer,RayReport,RayInspection} from '../../lib/ray/renderer';
import type {SceneSnapshot,BVH} from '../../lib/ray/types';
import RayDiagram from './RayDiagram';
import GuidedTasks from './GuidedTasks';
import PathPanel from './PathPanel';
import TransportControls from './TransportControls';
import {rayTitles,comparisonLabels} from './transportCopy';
import {rayLabHref} from '../../lib/ray/catalog';
import type {PathInspection,ReferenceMetrics} from '../../lib/ray/progressive';
import './ray.css';
const articleMap:Record<RayLesson,string>={rays:'ray-intersections',bvh:'ray-bvh',shadows:'ray-shadows',reflections:'ray-reflections',path:'path-tracing',mis:'ray-mis',denoise:'ray-denoising'};
const presetLabels={triangle:'三角形与解析球',scatter:'均匀散布',clusters:'簇状分布',overlap:'重叠包围盒',room:'彩色房间'};
export default function RayLab({lesson='rays',embedded=false}:{lesson?:RayLesson;embedded?:boolean}){
 const example=useRef<RayState|null>(null);
 const host=useRef<HTMLDivElement>(null),engine=useRef<RayRenderer|null>(null),stateRef=useRef(defaultRayState(lesson));
 const [state,setState]=useState(()=>defaultRayState(lesson)),[ready,setReady]=useState(false),[pending,setPending]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[paused,setPaused]=useState(false);
 const [device,setDevice]=useState('');
 const [pathInspection,setPathInspection]=useState<PathInspection|null>(null),[samples,setSamples]=useState(0),[refProgress,setRefProgress]=useState(0),[refReady,setRefReady]=useState(false),[referenceMetrics,setReferenceMetrics]=useState<ReferenceMetrics|null>(null),[playing,setPlaying]=useState(false),[replay,setReplay]=useState(-1),[gpu,setGPU]=useState<number|null>(null);
 const [inspection,setInspection]=useState<RayInspection|null>(null),[snapshot,setSnapshot]=useState<SceneSnapshot|null>(null),[bvh,setBVH]=useState<BVH|null>(null),[cpu,setCPU]=useState(0),[upload,setUpload]=useState(0),[share,setShare]=useState(''),[notice,setNotice]=useState('点击一个像素，冻结这条实际查询射线。');
 function report(r:RayReport){if(r.notice)setNotice(r.notice);if(r.device!==undefined)setDevice(r.device);if(r.pathInspection!==undefined)setPathInspection(r.pathInspection);if(r.sampleCount!==undefined)setSamples(r.sampleCount);if(r.progress!==undefined)setRefProgress(r.progress);if(r.referenceReady!==undefined)setRefReady(r.referenceReady);if(r.referenceMetrics!==undefined)setReferenceMetrics(r.referenceMetrics);if(r.playing!==undefined)setPlaying(r.playing);if(r.replaying!==undefined)setReplay(r.replaying);if(r.paused!==undefined)setPaused(r.paused);if(r.gpuMs!==undefined)setGPU(r.gpuMs);if(r.ready!==undefined)setReady(r.ready);if(r.pending!==undefined)setPending(r.pending);if(r.error)setError(r.error);if(r.state){stateRef.current=r.state;setState(r.state);}if(r.snapshot)setSnapshot(r.snapshot);if(r.bvh)setBVH(r.bvh);if(r.inspection!==undefined)setInspection(r.inspection);if(r.cpuMs!==undefined)setCPU(r.cpuMs);if(r.uploadMs!==undefined)setUpload(r.uploadMs);}
 useEffect(()=>{let cancelled=false;setError('');setReady(false);setPending(true);setPaused(false);setInspection(null);setPathInspection(null);setReferenceMetrics(null);setRefReady(false);setRefProgress(0);setSamples(0);const parsed=embedded?{state:defaultRayState(lesson)}:decodeRayState(location.hash,lesson);stateRef.current=parsed.state;setState(parsed.state);if(parsed.notice)setNotice(parsed.notice);
  import('../../lib/ray/renderer').then(({RayRenderer})=>{if(cancelled||!host.current)return;try{engine.current=new RayRenderer(host.current,parsed.state,report);}catch(e){setError(e instanceof Error?e.message:String(e));}}).catch(e=>setError(String(e)));
  const restore=()=>{if(embedded)return;const p=decodeRayState(location.hash,lesson);engine.current?.update(p.state);setNotice(p.notice??'已恢复完整场景与相机状态。');};window.addEventListener('hashchange',restore);
  return()=>{cancelled=true;window.removeEventListener('hashchange',restore);engine.current?.dispose();engine.current=null};
 },[lesson,attempt]);
 useEffect(()=>{if(embedded)return;const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const c=new AbortController();Promise.resolve(ctx.registerTool({name:'read_ray_experiment',description:'只读返回当前光追参数、GPU查询结果、独立CPU参考和BVH元信息。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('不接受参数');return {state:engine.current?.exportState()??stateRef.current,inspection:engine.current?.inspection,snapshot:engine.current?.snapshot,capabilities:engine.current?.capabilities(),bvh:engine.current?.bvh,pathInspection:engine.current?.pathInspection,progress:{samples:engine.current?.progressive?.count,referenceReady:engine.current?.progressive?.refReady,reference:engine.current?.progressive?.metrics,historyFrame:engine.current?.progressive?.reconstruction.lastFrame,replayTarget:engine.current?.seekTarget}};}},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[]);
 function change(patch:Partial<RayState>){const before=stateRef.current,next={...before,...patch};if(patch.preset&&patch.preset!==stateRef.current.preset)next.camera=rayCamera(patch.preset);engine.current?.update(next);if(next.lesson==='denoise'&&before.lesson==='denoise'&&Object.keys(patch).some(k=>!['view','exposure','compare','targetSpp','learning'].includes(k))){setPaused(false);engine.current?.seek(next.frame);}}
 function reset(){setPaused(false);engine.current?.setPaused(false);engine.current?.update(embedded&&example.current?structuredClone(example.current):defaultRayState(embedded?lesson:stateRef.current.lesson));setNotice('已恢复本节预设。');}
 async function sharing(){const current=stateRef.current;const url=new URL(rayLabHref(current.lesson,{...current,learning:current.learning??{article:articleMap[current.lesson],chapter:current.lesson==='bvh'?'traversal':'lab'}}),location.origin);setShare(url.href);try{await navigator.clipboard.writeText(url.href);setNotice('链接已复制；恢复时重新构建同一场景。')}catch{setNotice('请复制下方链接。')}}
 const active=state.lesson,advanced=!['rays','bvh'].includes(active);
 return <section className="ray-lab" data-ray-lesson={active}><header className="ray-lab-heading"><span className="eyebrow">{'RT-0'+(Object.keys(rayLessons).indexOf(active)+1)} / GPU 软件求交</span><h3>{rayTitles[active]}</h3><p>{advanced?'线性信号、实际 GPU 路径与明确的参考目标。固定像素中心，高样本仅减轻随机路径噪声。':'同一几何、同一射线。图像和日志由 GPU 内核生成，CPU 双精度暴力查询独立核对。'}</p></header>
 {embedded&&<GuidedTasks lesson={lesson} disabled={!ready||pending} onLoad={(patch)=>{const next={...defaultRayState(lesson),...patch};example.current=structuredClone(next);setPaused(false);engine.current?.setPaused(false);engine.current?.update(next);setNotice('已载入本实验的初始条件；展开参数可进一步检验预测。');}}/>}
 {!embedded&&<div className="ray-lesson-links">{Object.entries(rayLessons).map(([key,label])=><button key={key} aria-pressed={active===key} onClick={()=>{setPaused(false);engine.current?.setPaused(false);engine.current?.update(defaultRayState(key as RayLesson))}}>{label}</button>)}</div>}
 <div className="ray-topbar"><div className="small-tabs">{(['bvh','brute'] as const).map(t=><button key={t} aria-label={t==='bvh'?'BVH 查询':'暴力查询'} aria-pressed={state.traversal===t} onClick={()=>change({traversal:t})}>{t==='bvh'?'BVH':'暴力遍历'}</button>)}</div><button aria-pressed={state.compare} onClick={()=>change({compare:!state.compare})}>并排对照</button><span className="ray-status">{ready&&!pending?'WebGL2 · 就绪':error?'静态说明可用':'准备场景快照…'}</span></div>
 <div className="ray-viewport" ref={host}>{state.compare&&<div className={`ray-view-labels ${advanced?'four-panels':''}`}>{(advanced?comparisonLabels(active):['暴力遍历','BVH']).map(label=><span key={label}>{label}</span>)}</div>}{state.compare&&advanced&&active!=='reflections'&&!refReady&&<div className={`ray-reference-empty ${['path','mis'].includes(active)?'reference-third':''}`}>冻结当前条件后生成参考图</div>}{(!ready||error)&&<div className="ray-fallback"><p>{error||'准备同版本的几何与 BVH 数据…'}</p><p>{advanced?'静态说明：一次样本沿实际几何追踪，逐跳累乘 BSDF、方向权重与 PDF 的比值。独立样本在线性空间平均；几何改变后，旧估计失效。':'静态说明：射线与包围盒不相交时，可以排除其下所有图元；命中叶节点后，再检查实际几何。'}</p>{error&&<button onClick={()=>setAttempt(n=>n+1)}>重试</button>}</div>}{pending&&ready&&<div className="ray-pending">参数已改变，正在准备或等待计算；旧读数已隐藏。</div>}</div>
 <div className="ray-actions"><button disabled={!ready||pending} onClick={()=>engine.current?.pick()}>{advanced?'检查中心路径':'检查中心射线'}</button><button disabled={!ready} onClick={()=>{setPaused(!paused);engine.current?.setPaused(!paused)}}>{paused?'恢复更新':'暂停更新'}</button><button disabled={!ready} onClick={()=>engine.current?.step()}>单步计算</button><button onClick={reset}>恢复本节示例</button><button onClick={sharing}>分享实验</button></div><p className="fine ray-notice" role="status">{notice}</p>
 <details className="ray-parameters" open={embedded?undefined:true}><summary>{embedded?'调整本实验参数与参考':'实验参数与参考'}</summary>
 {!advanced&&<><div className="ray-controls"><label>场景<select aria-label="光追场景" value={state.preset} onChange={e=>change({preset:e.target.value as RayState['preset']})}>{Object.entries(presetLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>构建方式<select aria-label="BVH构建方式" value={state.builder} onChange={e=>change({builder:e.target.value as RayState['builder']})}><option value="median">中位数分割</option><option value="sah">12-bin SAH</option></select></label><label>查询语义<select aria-label="查询语义" value={state.query} onChange={e=>change({query:e.target.value as RayState['query']})}><option value="closest">最近命中 closest-hit</option><option value="any">任一遮挡 any-hit</option></select></label><label>图元预算 <output>{state.count}</output><input aria-label="图元预算" type="range" min="16" max="2048" step="16" value={state.count} onChange={e=>change({count:+e.target.value})}/></label><label>三角形平移 <output>{state.variant.toFixed(2)}</output><input aria-label="三角形平移" type="range" min="-1" max="1" step=".05" value={state.variant} disabled={state.preset!=='triangle'} onChange={e=>change({variant:+e.target.value})}/></label><label>显示内容<select aria-label="光追视图" value={state.view} onChange={e=>change({view:+e.target.value})}><option value="0">材质与形状</option><option value="1">几何法线</option><option value="2">命中距离</option><option value="3">查询成本</option></select></label></div>
 <details className="ray-advanced"><summary>射线区间与数值边界</summary><div className="ray-controls"><label>起点模式<select aria-label="射线起点" value={state.origin} onChange={e=>change({origin:e.target.value as RayState['origin']})}><option value="camera">相机</option><option value="surface">从主命中表面发射</option><option value="inside" disabled={!snapshot?.primitives.some(p=>p.kind==='sphere')}>从解析球内部发射</option></select></label><label>最小距离 tMin<input aria-label="射线最小距离" type="number" min="0" max=".1" step=".00001" value={state.tMin} onChange={e=>{const v=+e.target.value;if(Number.isFinite(v)&&v>=0&&v<state.tMax)change({tMin:v})}}/></label><label>最大距离 tMax<input aria-label="射线最大距离" type="number" min=".1" max="100" step=".1" value={state.tMax} onChange={e=>{const v=+e.target.value;if(Number.isFinite(v)&&v>state.tMin&&v<=100)change({tMax:v})}}/></label><label>表面偏移倍率 <output>{state.offsetScale.toFixed(1)}</output><input aria-label="表面偏移倍率" type="range" min="0" max="4" step=".1" value={state.offsetScale} onChange={e=>change({offsetScale:+e.target.value})}/></label><label>质量档<select aria-label="光追质量" value={state.quality} onChange={e=>change({quality:e.target.value as RayState['quality']})}><option value="standard">320 × 200</option><option value="low">160 × 100</option></select></label></div><p className="fine">表面/内部模式展示查询结果，不是普通相机图像。any-hit 只保证存在合法遮挡，不要求两种遍历返回同一图元。图元数量只影响分布场景；解析球和固定样章可能使用更少图元。</p></details></>}
 {advanced&&<TransportControls state={state} ready={ready} pending={pending} samples={samples} progress={refProgress} referenceReady={refReady} metrics={referenceMetrics} playing={playing} replay={replay} onChange={change} onReference={()=>engine.current?.generateReference()} onCancelReference={()=>{engine.current?.progressive?.cancelReference();engine.current?.progressReport();}} onMeasure={()=>engine.current?.measureReference()} onPlay={v=>engine.current?.play(v)} onFrame={n=>engine.current?.seek(n)} onNextFrame={()=>engine.current?.nextFrame()} onResetHistory={()=>engine.current?.seek(state.frame)}/>}
 </details>
 {advanced&&ready&&pathInspection&&!pending&&<PathPanel data={pathInspection} samples={samples} snapshot={snapshot} onSample={n=>engine.current?.setInspectSample(n)}/>}
 {bvh&&snapshot&&<div className="ray-stats"><span>实际图元 <b>{snapshot.primitives.length}</b></span><span>节点 / 深度 <b>{bvh.nodes.length} / {bvh.depth}</b></span><span>CPU 构建 <b>{bvh.buildMs.toFixed(2)} ms</b></span><span>上传提交 <b>{upload.toFixed(2)} ms</b></span><span>渲染提交 <b>{cpu.toFixed(2)} ms</b></span><span>GPU 核心执行 <b>{gpu===null?'不可用':gpu.toFixed(2)+' ms'}</b></span></div>}
 {!advanced&&ready&&inspection&&bvh&&snapshot&&!pending&&<section className="ray-inspection"><header><span className="eyebrow">实际 GPU 查询 / CPU 独立参考</span><h4>{['未命中','命中','预算溢出','非法结果'][inspection.status]??'未知结果'} <span className={inspection.consistent?'good':'bad'}>{inspection.consistent?'与 CPU 一致':'需要检查差异'}</span></h4></header><div className="ray-inspection-grid"><RayDiagram data={inspection} bvh={bvh} snapshot={snapshot}/><div><dl>{[['GPU t',inspection.status===1?inspection.t.toFixed(6):'—'],['CPU t',inspection.cpu.hit?.t.toFixed(6)??'—'],['最近距离差',state.query==='any'?'any-hit 不比较先后':inspection.distanceError?.toExponential(2)??'—'],['法线差',state.query==='closest'?inspection.normalError?.toExponential(2)??'—':'any-hit 不比较同一表面'],['GPU 重心 (a,b,c)',snapshot.primitives.find(p=>p.id===inspection.primitiveId)?.kind==='triangle'?inspection.barycentric.map(x=>x.toFixed(5)).join(', '):'非三角形 / 无命中'],['CPU 重心 (a,b,c)',inspection.cpu.hit&&snapshot.primitives.find(p=>p.id===inspection.cpu.hit?.primitiveId)?.kind==='triangle'?inspection.cpu.hit.barycentric.map(x=>x.toFixed(5)).join(', '):'—'],['图元 / 对象 / 材质',`${inspection.primitiveId} / ${inspection.objectId} / ${inspection.materialId}`],['正面命中',inspection.frontFace?'是':'否'],['节点访问 / 图元测试',`${inspection.nodes} / ${inspection.tests}`],['日志',inspection.truncated?'前256项，日志已截断':'完整'],['CPU 查询',inspection.cpu.status]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="fine">原点：{inspection.ray.origin.map(x=>x.toFixed(3)).join(', ')}<br/>方向：{inspection.ray.direction.map(x=>x.toFixed(4)).join(', ')}<br/>Ng：{inspection.normal.map(x=>x.toFixed(4)).join(', ')}</p><p className="ray-verdict">CPU 使用独立求交实现与 GPU 实际输入比较。日志截断只影响展示；计算溢出明确显示，不计为未命中。</p></div></div></section>}
 {device&&<p className="fine ray-device">设备：{device}。每幅图 {state.quality==='low'?'160 × 100':'320 × 200'}；{advanced&&active!=='reflections'?`${state.batch} spp / 更新 · `:''}CPU 为最近一次提交；GPU 仅计核心计算，不含选点读回和对照图生成。首次编译可能增加提交时间。</p>}
 {share&&<label className="ray-share">实验链接<input readOnly value={share} onFocus={e=>e.target.select()}/></label>}
 <footer className="ray-lab-footer"><span>世界空间 · 方向归一化 · 双面三角形 · t 为距离</span><a href={embedded?rayLabHref(active,{...state,learning:{article:articleMap[active],chapter:active==='bvh'?'traversal':'lab'}}):'/articles/'+(state.learning?.article??articleMap[active])+'/#'+(state.learning?.chapter??'lab')}>{embedded?'携当前状态打开完整实验':'返回文章章节'}</a></footer>
 </section>;
}
