import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],passed=[];await mkdir('test-results',{recursive:true});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.addInitScript(()=>{window.__tools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.__tools[t.name]=t}}});});
const base=process.env.TEST_URL||'http://127.0.0.1:4321';const read=()=>page.evaluate(()=>window.__tools.read_ray_experiment.execute({}));const ready=()=>page.waitForFunction(()=>document.querySelector('.ray-status')?.textContent.includes('就绪'));
async function test(name,fn){await fn();passed.push(name);console.log('PASS',name)}
try{
 await page.goto(base+'/labs/rays/');await ready();
 await test('GPU queries agree with independent CPU oracle at selected pixels',async()=>{const canvas=page.locator('.ray-viewport>canvas');for(const preset of ['triangle','scatter','clusters','overlap','room']){await page.getByLabel('光追场景',{exact:true}).selectOption(preset);await ready();const box=await canvas.boundingBox();for(const [u,v] of [[.5,.5],[.4,.6],[.6,.55]]){await canvas.click({position:{x:box.width*u,y:box.height*(1-v)}});await page.locator('.ray-inspection').waitFor();const r=await read();assert.ok(r.inspection.consistent,JSON.stringify({preset,i:r.inspection}));}}});
 await test('median, SAH and brute preserve closest result',async()=>{await page.getByLabel('光追场景',{exact:true}).selectOption('scatter');await ready();await page.getByRole('button',{name:'检查中心射线',exact:true}).click();const a=(await read()).inspection;await page.getByLabel('BVH构建方式',{exact:true}).selectOption('sah');await ready();await page.getByRole('button',{name:'检查中心射线',exact:true}).click();const b=(await read()).inspection;assert.equal(a.primitiveId,b.primitiveId);assert.ok(Math.abs(a.t-b.t)<.001);await page.getByRole('button',{name:'暴力查询',exact:true}).click();await ready();assert.ok((await read()).inspection.consistent);await page.getByRole('button',{name:'BVH 查询',exact:true}).click();});
 await test('any-hit only checks visibility identity',async()=>{await page.getByLabel('查询语义',{exact:true}).selectOption('any');await ready();await page.getByRole('button',{name:'检查中心射线',exact:true}).click();assert.ok((await read()).inspection.consistent);await page.getByLabel('查询语义',{exact:true}).selectOption('closest');await ready();});
 await test('node traversal has actual GPU events',async()=>{await page.getByRole('button',{name:'检查中心射线',exact:true}).click();const r=await read();assert.ok(r.inspection.events.length>0);assert.ok(r.inspection.events.every(e=>e.node>=0&&e.node<r.bvh.nodes.length));await page.getByLabel('访问事件',{exact:true}).fill('1');await page.screenshot({path:'test-results/ray-bvh.png',fullPage:true});});
 await test('share roundtrip restores camera and construction settings',async()=>{await page.getByRole('button',{name:'分享实验',exact:true}).click();const link=await page.locator('.ray-share input').inputValue(),before=(await read()).state;await page.goto(link);await ready();assert.deepEqual((await read()).state,{...before,learning:{article:'ray-bvh',chapter:'traversal'}});});
 await test('pause edits hide old inspection until step',async()=>{await page.getByRole('button',{name:'检查中心射线',exact:true}).click();await page.getByRole('button',{name:'暂停更新',exact:true}).click();await page.getByRole('button',{name:'暴力查询',exact:true}).click();assert.equal(await page.locator('.ray-inspection').count(),0);await page.getByRole('button',{name:'单步计算',exact:true}).click();await page.locator('.ray-inspection').waitFor();assert.ok((await read()).inspection.consistent);await page.getByRole('button',{name:'恢复更新',exact:true}).click();});
 await test('comparison and mobile layout are usable',async()=>{await page.getByRole('button',{name:'并排对照',exact:true}).click();await ready();await page.screenshot({path:'test-results/ray-compare.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/ray-mobile.png',fullPage:true});});
 await test('articles remain readable without JavaScript',async()=>{const context=await browser.newContext({javaScriptEnabled:false});const p=await context.newPage();for(const slug of ['ray-intersections','ray-bvh']){await p.goto(base+'/articles/'+slug+'/');assert.ok(await p.locator('h1').innerText());assert.ok(await p.locator('.ray-lab').count());}await context.close();});
 assert.deepEqual(errors,[]);await writeFile('test-results/rays-results.json',JSON.stringify({passed,errors},null,2));console.log('ALL',passed.length,'ray scenarios passed');
}catch(e){console.log('ERRORS',errors);await page.screenshot({path:'test-results/ray-failure.png',fullPage:true}).catch(()=>{});throw e;}finally{await browser.close();}
