import ObservationGuide from '../reading/ObservationGuide';
import {shadowGuides,filteringGuides} from '../reading/guides';
import {useEffect,useRef,useState} from 'react';
import type {ShadowLesson,ShadowReport,ShadowState} from '../../lib/shadow/types';
import {defaultShadowState,decodeShadowState,shadowLabHref} from '../../lib/shadow/state';
import type {ShadowWebGPURenderer as ShadowRenderer} from '../../lib/shadow/webgpu-renderer';
import Inspection from './ShadowInspection';
import './shadow.css';
const names={hard:'硬阴影',pcf:'PCF',pcss:'PCSS'};
const taskSets={
 mapping:[{name:'从光源看',question:'眼睛看得见，光源也看得见吗？',action:'先观察光图，再切回“场景着色”，点击接收面。比较接收点深度与光图中最近表面的深度。',patch:{preset:'contact',algorithm:'hard',view:'map'}},{name:'分辨率与覆盖',question:'同一张图装进更多世界，阴影边缘会怎样？',action:'保持相机，先将光图从 128 提到 512，再只改变光源视角。看细柱阴影和每个纹素覆盖的范围。',patch:{preset:'steps',algorithm:'hard',resolution:128,view:'visibility'}},{name:'偏移的代价',question:'消除自遮挡时，会不会把接触阴影一起推开？',action:'从零偏移开始，缓慢增加深度偏移；再开启接收平面修正。观察条纹与接触处，而不是只追求画面无瑕疵。',patch:{preset:'steps',algorithm:'hard',bias:0,planeCorrection:false,view:'lit'}}],
 filtering:[{name:'先比较再平均',question:'模糊深度和过滤可见性，为什么不是同一个结果？',action:'选择 PCF，改变固定滤波半径；检查多个样本，数一数可见的 1 与遮挡的 0。',patch:{preset:'steps',algorithm:'pcf',filterRadius:2,resolution:256,view:'visibility'}},{name:'接触半影',question:'PCSS 的滤波半径，怎样随灯面和遮挡距离变化？',action:'打开四格对照，分别改变灯面半边长和遮挡板高度；检查平均遮挡距离及最终滤波半径。',patch:{preset:'contact',algorithm:'pcss',height:.4,lightSize:.7,compare:true}},{name:'单层深度的边界',question:'多个遮挡层能用一个平均距离代表吗？',action:'在叠片场景选地面阴影边缘，生成这个点的完整几何面积参考。调节灯面，比较误差及覆盖状态。',patch:{preset:'layers',algorithm:'pcss',height:1.8,lightSize:1,compare:true,view:'visibility'}}]
} satisfies Record<ShadowLesson,Array<{name:string;question:string;action:string;patch:Partial<ShadowState>}>>;
export default function ShadowLab({lesson='mapping',embedded=false}:{lesson?:ShadowLesson;embedded?:boolean}){
 const host=useRef<HTMLDivElement>(null),engine=useRef<ShadowRenderer|null>(null),stateRef=useRef(defaultShadowState(lesson)),reportRef=useRef<ShadowReport>({}),example=useRef<ShadowState|null>(null);
 const [state,setState]=useState(()=>defaultShadowState(lesson)),[report,setReport]=useState<ShadowReport>({}),[attempt,setAttempt]=useState(0),[task,setTask]=useState(0),[taskLoaded,setTaskLoaded]=useState(false),[notice,setNotice]=useState('拖动场景旋转；点击接收表面，检查实际深度比较。'),[link,setLink]=useState('');
 const active=state.lesson,ready=!!report.ready,pending=!!report.pending,paused=!!report.paused,inspection=report.inspection;
 const receiving=!!report.referenceProgress&&report.referenceProgress<1;
 function receive(next:ShadowReport){reportRef.current={...reportRef.current,...next};setReport(reportRef.current);if(next.state){stateRef.current=next.state;setState(next.state);}}
 useEffect(()=>{let disposed=false;const decoded=attempt>0?{state:stateRef.current}:embedded?{state:defaultShadowState(lesson)}:decodeShadowState(location.hash,lesson);stateRef.current=decoded.state;setState(decoded.state);reportRef.current={ready:false,pending:true};setReport(reportRef.current);if(decoded.notice)setNotice(decoded.notice);
  import('../../lib/shadow/webgpu-renderer').then(async({ShadowWebGPURenderer})=>{if(disposed||!host.current)return;try{const created=await ShadowWebGPURenderer.create(host.current,decoded.state,receive);if(disposed){created.dispose();return;}engine.current=created;}catch(e){receive({error:e instanceof Error?e.message:String(e),ready:false,pending:false});}}).catch(e=>receive({error:String(e),ready:false,pending:false}));
  const restore=()=>{if(embedded)return;const parsed=decodeShadowState(location.hash,lesson);engine.current?.update(parsed.state);setNotice(parsed.notice??'已恢复阴影实验参数与相机。');};window.addEventListener('hashchange',restore);
  return()=>{disposed=true;window.removeEventListener('hashchange',restore);engine.current?.dispose();engine.current=null};
 },[lesson,attempt]);
 useEffect(()=>{if(embedded)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_shadow_experiment',description:'只读返回阴影实验参数、实际GPU采样检查和独立CPU参考。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');return {...reportRef.current,state:engine.current?.exportState()??stateRef.current}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 const change=(patch:Partial<ShadowState>)=>engine.current?.update({...stateRef.current,...patch});
 function load(index:number){const next={...defaultShadowState(active),...taskSets[active][index].patch};setTask(index);setTaskLoaded(true);example.current=structuredClone(next);engine.current?.setPaused(false);engine.current?.update(next);setNotice('已载入任务初始条件；后续滚动不会覆盖你的修改。');}
 function reset(){engine.current?.setPaused(false);engine.current?.update(example.current?.lesson===active?structuredClone(example.current):defaultShadowState(active));setNotice('已恢复本节示例。');}
 async function share(){const current=stateRef.current;const url=new URL(shadowLabHref(current.lesson,{...current,learning:current.learning??{article:current.lesson==='mapping'?'shadow-mapping':'pcf-pcss',chapter:'lab'}}),location.origin).href;setLink(url);try{await navigator.clipboard.writeText(url);setNotice('链接已复制；接收者从相同场景、相机和参数开始。')}catch{setNotice('复制下方链接即可分享当前条件。')}}
 const brief=taskSets[active][Math.min(task,2)];
 return <section className="shadow-lab" data-shadow-lesson={active}>
  <header className="shadow-heading"><span className="eyebrow">{active==='mapping'?'SH-01 / SHADOW MAPPING':'SH-02 / PCF & PCSS'} · 算法实验</span><h3>{active==='mapping'?'同一个表面，换到光源的视角。':'边缘变软之前，先看每个样本说了什么。'}</h3><p>真实网格光栅化 → 光源深度图 → 接收面查询。选点读数来自实际 Shader；CPU 几何参考另行计算。</p></header>
  {!embedded&&<div className="shadow-mode"><button disabled={!ready} aria-pressed={active==='mapping'} onClick={()=>{engine.current?.setPaused(false);engine.current?.update(defaultShadowState('mapping'));setTask(0);setTaskLoaded(false);example.current=null}}>阴影贴图</button><button disabled={!ready} aria-pressed={active==='filtering'} onClick={()=>{engine.current?.setPaused(false);engine.current?.update(defaultShadowState('filtering'));setTask(0);setTaskLoaded(false);example.current=null}}>PCF / PCSS</button></div>}
  <div className="shadow-task"><div className="shadow-small-tabs">{taskSets[active].map((t,i)=><button key={t.name} disabled={!ready||pending} aria-pressed={taskLoaded&&task===i} onClick={()=>load(i)}>{i+1} · {t.name}</button>)}</div><h4>{brief.question}</h4><p>{brief.action}</p>{!taskLoaded&&<p className="fine">点击任务按钮载入起点；当前也可以自由探索。</p>}</div>
  <ObservationGuide key={active+task} {...(active==='mapping'?shadowGuides:filteringGuides)[task]}/>
  <div className="shadow-toolbar"><div className="shadow-small-tabs">{Object.entries(names).map(([key,label])=><button key={key} disabled={!ready} aria-pressed={state.algorithm===key} onClick={()=>change({algorithm:key as ShadowState['algorithm']})}>{label}</button>)}</div><button disabled={!ready} aria-pressed={state.compare} onClick={()=>change({compare:!state.compare})}>四格对照</button><span role="status">{report.error?'静态说明可读':!ready?'初始化中…':pending?'等待当前状态计算':'WebGPU · 就绪'}</span></div>
  <div className="shadow-viewport" ref={host}>
   {state.compare&&<div className="shadow-pane-labels">{['硬阴影','固定半径 PCF','PCSS','真实光图 · 线性距离'].map(s=><span key={s}>{s}</span>)}</div>}
   {ready&&!pending&&inspection&&<div className="shadow-markers" aria-hidden="true">{(state.compare?[0,1,2]:(state.view==='map'?[]:[0])).map(panel=><span className="shadow-marker" key={panel} style={{left:`${(inspection.uv[0]+(state.compare?panel%2:0))*100/(state.compare?2:1)}%`,top:`${(1-inspection.uv[1]+(state.compare?Math.floor(panel/2):0))*100/(state.compare?2:1)}%`}}/>)}{(state.compare||state.view==='map')&&inspection.lightUv.every(v=>v>=0&&v<1)&&<span className="shadow-marker map" style={{left:`${state.compare?50+inspection.lightUv[0]*50:inspection.lightUv[0]*100}%`,top:`${state.compare?50+(1-inspection.lightUv[1])*50:(1-inspection.lightUv[1])*100}%`}}/>}</div>}
   {!ready&&<div className="shadow-fallback"><strong>{report.error??'准备网格与光栅深度纹理…'}</strong><svg viewBox="0 0 470 90" role="img" aria-label="原理示意：从光源渲染深度图，再与接收点比较"><g fill="#f7fafc" stroke="#9eb8c7"><rect x="5" y="15" width="105" height="42" rx="4"/><rect x="165" y="15" width="140" height="42" rx="4"/><rect x="360" y="15" width="105" height="42" rx="4"/></g><g stroke="#537d91"><path d="M118 36h36m-7-5 7 5-7 5 M313 36h36m-7-5 7 5-7 5"/></g><g fill="#365f74" textAnchor="middle" fontSize="12"><text x="57" y="40">光源视角</text><text x="235" y="40">光图最近深度</text><text x="412" y="40">接收点比较</text><text x="235" y="80">原理示意 · 不是 GPU 执行结果</text></g></svg><p>静态步骤：把接收点变换到光源裁剪空间，透视除法后找到光图 UV，再比较同一深度约定下的前后关系。PCF 平均比较结果；PCSS 根据遮挡距离选择过滤范围。</p>{report.error&&<button onClick={()=>setAttempt(n=>n+1)}>重试阴影实验</button>}</div>}
   {pending&&ready&&<div className="shadow-pending">输入已变化，旧检查与参考不再显示。单步或恢复后计算当前状态。</div>}
  </div>
  <div className="shadow-actions"><button disabled={!ready||pending||(state.view==='map'&&!state.compare)} onClick={()=>active==='filtering'?engine.current?.pick(.62,.35):engine.current?.pick(.53,.3)}>检查地面示例点</button><button disabled={!ready} onClick={()=>engine.current?.setPaused(!paused)}>{paused?'恢复更新':'暂停更新'}</button><button disabled={!ready} onClick={()=>engine.current?.step()}>单步计算</button><button disabled={!ready} onClick={reset}>恢复本节示例</button><button onClick={share}>分享阴影实验</button></div>
  <p className="shadow-notice fine" role="status">{state.view==='map'&&!state.compare?'光图使用光源坐标；切回场景视图后选点。':notice} 橙色表示光图窗口越界，或接收平面修正无法提供有效比较。</p>
  <fieldset className="shadow-fieldset" disabled={!ready}><div className="shadow-controls">
   <label>显示信号<select aria-label="阴影显示信号" value={state.view} onChange={e=>change({view:e.target.value as ShadowState['view']})}><option value="lit">场景着色</option><option value="visibility">可见度 · 1 亮 / 0 暗</option><option value="map">光源深度图</option></select></label>
   <label>光图分辨率<select aria-label="光图分辨率" value={state.resolution} onChange={e=>change({resolution:+e.target.value as ShadowState['resolution']})}>{[128,256,512,1024].map(v=><option value={v} key={v}>{v} × {v}</option>)}</select></label>
   {active==='mapping'?<label>光源视角 <output>{state.fov}°</output><input aria-label="光源视角" type="range" min="40" max="110" step="1" value={state.fov} onChange={e=>change({fov:+e.target.value})}/></label>:<><label>灯面半边长 <output>{state.lightSize.toFixed(2)}</output><input aria-label="灯面半边长" type="range" min="0" max="1.5" step=".05" value={state.lightSize} onChange={e=>change({lightSize:+e.target.value})}/></label><label>遮挡板高度 <output>{state.height.toFixed(2)}</output><input aria-label="遮挡板高度" type="range" min=".15" max="2.5" step=".05" value={state.height} onChange={e=>change({height:+e.target.value})}/></label><label>PCF 固定半径 <output>{state.filterRadius.toFixed(1)} texels</output><input aria-label="PCF 固定半径" type="range" min="0" max="12" step=".5" value={state.filterRadius} onChange={e=>change({filterRadius:+e.target.value})}/></label></>}
  </div>
  <details className="shadow-options" open={embedded?undefined:true}><summary>场景、偏移与更多参数</summary><div className="shadow-controls">
   <label>场景<select aria-label="阴影场景" value={state.preset} onChange={e=>change({preset:e.target.value as ShadowState['preset']})}><option value="contact">接触与悬空</option><option value="steps">细柱与斜面</option><option value="layers">多层遮挡</option></select></label>
   <label>深度偏移 <output>{state.bias.toFixed(3)} 世界单位</output><input aria-label="阴影深度偏移" type="range" min="0" max=".08" step=".001" value={state.bias} onChange={e=>change({bias:+e.target.value})}/></label>
   <label className="shadow-check"><input aria-label="接收平面修正" type="checkbox" checked={state.planeCorrection} onChange={e=>change({planeCorrection:e.target.checked})}/> 按实际光图纹素中心修正接收平面</label>
   {active==='filtering'&&<label>光源视角 <output>{state.fov}°</output><input aria-label="光源视角" type="range" min="40" max="110" step="1" value={state.fov} onChange={e=>change({fov:+e.target.value})}/></label>}
   <label>参考采样种子<input aria-label="阴影参考种子" type="number" min="0" max="65535" value={state.seed} onChange={e=>{const n=+e.target.value;if(Number.isInteger(n)&&n>=0&&n<=65535)change({seed:n})}}/></label>
  </div><p className="fine">偏移作用在光源轴向距离上，再转换为深度比较阈值。它与射线起点偏移是不同操作。接收平面修正减少斜面纹素错位误差，曲面和几何轮廓仍有局限。</p></details></fieldset>
  {ready&&!pending&&inspection&&<Inspection data={inspection} resolution={state.resolution} algorithm={names[state.algorithm]}/>}
  <section className="shadow-reference"><h4>选中点的完整几何参考</h4><p>从同一个世界表面点，均匀采样方灯面积并用独立 CPU 三角形求交。比较面积可见比例；不包含材质、余弦和距离权重，也不是全图参考。</p>{state.lightSize===0&&<p className="fine">灯面尺寸为 0 时按点光退化处理，参考中的所有方向相同。</p>}<div className="shadow-actions"><button disabled={!ready||pending||!inspection||receiving} onClick={()=>engine.current?.generateReference()}>生成单点 1024 样本参考</button>{receiving&&<button onClick={()=>engine.current?.cancelReference()}>取消单点参考</button>}</div>{receiving&&<progress aria-label="单点参考进度" max="1" value={report.referenceProgress}/>}
   {report.reference&&!pending&&inspection&&<dl className="shadow-reference-values"><div><dt>完整几何面积可见率</dt><dd>{report.reference.value.toFixed(5)}</dd></div><div><dt>当前方法 / 参考绝对差</dt><dd>{inspection.covered?Math.abs(inspection.visibility-report.reference.value).toFixed(5):'当前方法无法有效比较'}</dd></div><div><dt>512 → 1024 变化</dt><dd>{report.reference.convergence.toExponential(2)}</dd></div></dl>}
   <p className="fine">更改接收点、几何或灯面后参考失效。更改光图分辨率与过滤方法可对照同一物理目标。硬阴影查询中心光线，PCF 是纹素过滤，二者与面积可见率的差不能全部归因为实现错误。</p>
  </section>
  <div className="shadow-stats"><span>图像 <b>320 × 200 / 格</b></span><span>显式三角形 <b>{report.triangles??'—'}</b></span><span>CPU 提交 <b>{report.cpuMs===undefined?'—':report.cpuMs.toFixed(2)+' ms'}</b></span><span>GPU 阴影查询 <b>{report.gpuMs==null?'不可用':report.gpuMs.toFixed(2)+' ms'}</b></span></div>
  <p className="fine shadow-device">{report.device?`设备：${report.device}。`:''}GPU 时间只覆盖阴影查询，不含光源与主相机光栅、单点读回或 CPU 参考；图像分辨率与光图分辨率分别记录。</p>
  {link&&<label className="shadow-share">实验链接<input aria-label="阴影实验分享链接" readOnly value={link} onFocus={e=>e.target.select()}/></label>}
  <footer className="shadow-footer"><span>深度比较 → 可见性过滤 → 半影近似</span><a href={embedded?shadowLabHref(active,{...state,learning:{article:active==='mapping'?'shadow-mapping':'pcf-pcss',chapter:'lab'}}):`/articles/${state.learning?.article??(active==='mapping'?'shadow-mapping':'pcf-pcss')}/#${state.learning?.chapter??'lab'}`}>{embedded?'携状态打开完整实验室':'返回文章章节'}</a></footer>
 </section>;
}
